-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: apb_slave   variant: long_names   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity apb_regs is
  generic (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 4
  );
  port (
    axi_aclk    : in  std_logic;
    axi_aresetn : in  std_logic;
    paddr       : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    psel        : in  std_logic;
    penable     : in  std_logic;
    pwrite      : in  std_logic;
    pwdata      : in  std_logic_vector(31 downto 0);
    pready      : out std_logic;
    prdata      : out std_logic_vector(31 downto 0);
    pslverr     : out std_logic
  );
end entity apb_regs;

architecture rtl of apb_regs is

  type t_registers is array (0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal s_reg_file_r : t_registers;
  signal s_index : natural;
  signal s_prdata_r : std_logic_vector(31 downto 0);
  signal s_pslverr_r : std_logic;

begin

  -- No wait states: the access phase always completes.
  pready <= '1';

  s_index <= to_integer(unsigned(paddr(G_ADDR_WIDTH - 1 downto 2)));

  p_apb : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_reg_file_r <= (others => (others => '0'));
      s_prdata_r <= (others => '0');
      s_pslverr_r <= '0';
    elsif rising_edge(axi_aclk) then
      -- A transfer completes only in the access phase, when PSEL
      -- and PENABLE are both high. Acting in the setup phase is
      -- the classic APB mistake.
      if psel = '1' and penable = '1' then
        if s_index < G_REGISTERS then
          s_pslverr_r <= '0';
          if pwrite = '1' then
            s_reg_file_r(s_index) <= pwdata;
          else
            s_prdata_r <= s_reg_file_r(s_index);
          end if;
        else
          -- Outside the register file: report the error rather
          -- than aliasing onto a real register.
          s_pslverr_r <= '1';
          s_prdata_r <= (others => '0');
        end if;
      end if;
    end if;
  end process p_apb;

  prdata  <= s_prdata_r;
  pslverr <= s_pslverr_r;

end architecture rtl;
