-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: apb_slave   variant: upper_sync_high   case: name_gold_name

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY gold_name IS
  GENERIC (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 4
  );
  PORT (
    clk     : IN  std_logic;
    rst     : IN  std_logic;
    paddr   : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    psel    : IN  std_logic;
    penable : IN  std_logic;
    pwrite  : IN  std_logic;
    pwdata  : IN  std_logic_vector(31 DOWNTO 0);
    pready  : OUT std_logic;
    prdata  : OUT std_logic_vector(31 DOWNTO 0);
    pslverr : OUT std_logic
  );
END ENTITY gold_name;

ARCHITECTURE rtl OF gold_name IS

  TYPE t_registers IS ARRAY (0 TO G_REGISTERS - 1) OF std_logic_vector(31 DOWNTO 0);

  SIGNAL reg_file_r : t_registers;
  SIGNAL index : natural;
  SIGNAL prdata_r : std_logic_vector(31 DOWNTO 0);
  SIGNAL pslverr_r : std_logic;

BEGIN

  -- No wait states: the access phase always completes.
  pready <= '1';

  index <= TO_INTEGER(UNSIGNED(paddr(G_ADDR_WIDTH - 1 DOWNTO 2)));

  p_apb : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        reg_file_r <= (OTHERS => (OTHERS => '0'));
        prdata_r <= (OTHERS => '0');
        pslverr_r <= '0';
      ELSE
        -- A transfer completes only in the access phase, when PSEL
        -- and PENABLE are both high. Acting in the setup phase is
        -- the classic APB mistake.
        IF psel = '1' AND penable = '1' THEN
          IF index < G_REGISTERS THEN
            pslverr_r <= '0';
            IF pwrite = '1' THEN
              reg_file_r(index) <= pwdata;
            ELSE
              prdata_r <= reg_file_r(index);
            END IF;
          ELSE
            -- Outside the register file: report the error rather
            -- than aliasing onto a real register.
            pslverr_r <= '1';
            prdata_r <= (OTHERS => '0');
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS p_apb;

  prdata  <= prdata_r;
  pslverr <= pslverr_r;

END ARCHITECTURE rtl;
