-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: apb_slave   variant: default   case: registers_1

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity apb_regs is
  generic (
    G_REGISTERS : positive := 1;
    G_ADDR_WIDTH : positive := 3
  );
  port (
    clk     : in  std_logic;
    rst_n   : in  std_logic;
    paddr   : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    psel    : in  std_logic;
    penable : in  std_logic;
    pwrite  : in  std_logic;
    pwdata  : in  std_logic_vector(31 downto 0);
    pready  : out std_logic;
    prdata  : out std_logic_vector(31 downto 0);
    pslverr : out std_logic
  );
end entity apb_regs;

architecture rtl of apb_regs is

  type t_registers is array (0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal reg_file_r : t_registers;
  signal index : natural;
  signal prdata_r : std_logic_vector(31 downto 0);
  signal pslverr_r : std_logic;

begin

  -- No wait states: the access phase always completes.
  pready <= '1';

  index <= to_integer(unsigned(paddr(G_ADDR_WIDTH - 1 downto 2)));

  p_apb : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      reg_file_r <= (others => (others => '0'));
      prdata_r <= (others => '0');
      pslverr_r <= '0';
    elsif rising_edge(clk) then
      -- A transfer completes only in the access phase, when PSEL
      -- and PENABLE are both high. Acting in the setup phase is
      -- the classic APB mistake.
      if psel = '1' and penable = '1' then
        if index < G_REGISTERS then
          pslverr_r <= '0';
          if pwrite = '1' then
            reg_file_r(index) <= pwdata;
          else
            prdata_r <= reg_file_r(index);
          end if;
        else
          -- Outside the register file: report the error rather
          -- than aliasing onto a real register.
          pslverr_r <= '1';
          prdata_r <= (others => '0');
        end if;
      end if;
    end if;
  end process p_apb;

  prdata  <= prdata_r;
  pslverr <= pslverr_r;

end architecture rtl;
