-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: avalon_mm_slave   variant: upper_sync_high   case: registers_1

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY avmm_regs IS
  GENERIC (
    G_REGISTERS : positive := 1;
    G_ADDR_WIDTH : positive := 1
  );
  PORT (
    clk             : IN  std_logic;
    rst             : IN  std_logic;
    avs_address     : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    avs_read        : IN  std_logic;
    avs_write       : IN  std_logic;
    avs_writedata   : IN  std_logic_vector(31 DOWNTO 0);
    avs_byteenable  : IN  std_logic_vector(3 DOWNTO 0);
    avs_readdata    : OUT std_logic_vector(31 DOWNTO 0);
    avs_waitrequest : OUT std_logic
  );
END ENTITY avmm_regs;

ARCHITECTURE rtl OF avmm_regs IS

  TYPE t_registers IS ARRAY (natural RANGE 0 TO G_REGISTERS - 1) OF std_logic_vector(31 DOWNTO 0);

  SIGNAL reg_file_r : t_registers;
  SIGNAL index : natural;
  SIGNAL readdata_r : std_logic_vector(31 DOWNTO 0);

BEGIN

  -- Zero wait states: the transfer completes in the cycle it is
  -- presented, so no read latency has to be kept in step.
  avs_waitrequest <= '0';

  index <= TO_INTEGER(UNSIGNED(avs_address));

  p_avalon : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        reg_file_r <= (OTHERS => (OTHERS => '0'));
        readdata_r <= (OTHERS => '0');
      ELSE
        IF avs_write = '1' THEN
          IF index < G_REGISTERS THEN
            -- Byte enables: ignoring them corrupts a read modify
            -- write from software.
            FOR byte IN 0 TO 3 LOOP
              IF avs_byteenable(byte) = '1' THEN
                reg_file_r(index)(byte * 8 + 7 DOWNTO byte * 8) <=
                  avs_writedata(byte * 8 + 7 DOWNTO byte * 8);
              END IF;
            END LOOP;
          END IF;
        END IF;

        IF avs_read = '1' THEN
          IF index < G_REGISTERS THEN
            readdata_r <= reg_file_r(index);
          ELSE
            -- Avalon-MM has no error response, so an unmapped read
            -- returns zero rather than whatever was last there.
            readdata_r <= (OTHERS => '0');
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS p_avalon;

  avs_readdata <= readdata_r;

END ARCHITECTURE rtl;
