-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: avalon_mm_slave   variant: no_reset   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity gold_name is
  generic (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 2
  );
  port (
    clk             : in  std_logic;
    avs_address     : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    avs_read        : in  std_logic;
    avs_write       : in  std_logic;
    avs_writedata   : in  std_logic_vector(31 downto 0);
    avs_byteenable  : in  std_logic_vector(3 downto 0);
    avs_readdata    : out std_logic_vector(31 downto 0);
    avs_waitrequest : out std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

  type t_registers is array (natural range 0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal reg_file_r : t_registers;
  signal index : natural;
  signal readdata_r : std_logic_vector(31 downto 0);

begin

  -- Zero wait states: the transfer completes in the cycle it is
  -- presented, so no read latency has to be kept in step.
  avs_waitrequest <= '0';

  index <= to_integer(unsigned(avs_address));

  p_avalon : process (clk) is
  begin
    if rising_edge(clk) then
      if avs_write = '1' then
        if index < G_REGISTERS then
          -- Byte enables: ignoring them corrupts a read modify
          -- write from software.
          for byte in 0 to 3 loop
            if avs_byteenable(byte) = '1' then
              reg_file_r(index)(byte * 8 + 7 downto byte * 8) <=
                avs_writedata(byte * 8 + 7 downto byte * 8);
            end if;
          end loop;
        end if;
      end if;

      if avs_read = '1' then
        if index < G_REGISTERS then
          readdata_r <= reg_file_r(index);
        else
          -- Avalon-MM has no error response, so an unmapped read
          -- returns zero rather than whatever was last there.
          readdata_r <= (others => '0');
        end if;
      end if;
    end if;
  end process p_avalon;

  avs_readdata <= readdata_r;

end architecture rtl;
