-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: avalon_mm_slave   variant: long_names   case: registers_256

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity avmm_regs is
  generic (
    G_REGISTERS : positive := 256;
    G_ADDR_WIDTH : positive := 8
  );
  port (
    axi_aclk        : in  std_logic;
    axi_aresetn     : in  std_logic;
    avs_address     : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    avs_read        : in  std_logic;
    avs_write       : in  std_logic;
    avs_writedata   : in  std_logic_vector(31 downto 0);
    avs_byteenable  : in  std_logic_vector(3 downto 0);
    avs_readdata    : out std_logic_vector(31 downto 0);
    avs_waitrequest : out std_logic
  );
end entity avmm_regs;

architecture rtl of avmm_regs is

  type t_registers is array (natural range 0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal s_reg_file_r : t_registers;
  signal s_index : natural;
  signal s_readdata_r : std_logic_vector(31 downto 0);

begin

  -- Zero wait states: the transfer completes in the cycle it is
  -- presented, so no read latency has to be kept in step.
  avs_waitrequest <= '0';

  s_index <= to_integer(unsigned(avs_address));

  p_avalon : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_reg_file_r <= (others => (others => '0'));
      s_readdata_r <= (others => '0');
    elsif rising_edge(axi_aclk) then
      if avs_write = '1' then
        if s_index < G_REGISTERS then
          -- Byte enables: ignoring them corrupts a read modify
          -- write from software.
          for byte in 0 to 3 loop
            if avs_byteenable(byte) = '1' then
              s_reg_file_r(s_index)(byte * 8 + 7 downto byte * 8) <=
                avs_writedata(byte * 8 + 7 downto byte * 8);
            end if;
          end loop;
        end if;
      end if;

      if avs_read = '1' then
        if s_index < G_REGISTERS then
          s_readdata_r <= s_reg_file_r(s_index);
        else
          -- Avalon-MM has no error response, so an unmapped read
          -- returns zero rather than whatever was last there.
          s_readdata_r <= (others => '0');
        end if;
      end if;
    end if;
  end process p_avalon;

  avs_readdata <= s_readdata_r;

end architecture rtl;
