-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axi4lite_slave   variant: upper_sync_high   case: registers_256

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY axi_regs IS
  GENERIC (
    G_REGISTERS : positive := 256;
    G_ADDR_WIDTH : positive := 10
  );
  PORT (
    clk           : IN  std_logic;
    rst           : IN  std_logic;
    s_axi_awaddr  : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    s_axi_awvalid : IN  std_logic;
    s_axi_awready : OUT std_logic;
    s_axi_wdata   : IN  std_logic_vector(31 DOWNTO 0);
    s_axi_wstrb   : IN  std_logic_vector(3 DOWNTO 0);
    s_axi_wvalid  : IN  std_logic;
    s_axi_wready  : OUT std_logic;
    s_axi_bresp   : OUT std_logic_vector(1 DOWNTO 0);
    s_axi_bvalid  : OUT std_logic;
    s_axi_bready  : IN  std_logic;
    s_axi_araddr  : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    s_axi_arvalid : IN  std_logic;
    s_axi_arready : OUT std_logic;
    s_axi_rdata   : OUT std_logic_vector(31 DOWNTO 0);
    s_axi_rresp   : OUT std_logic_vector(1 DOWNTO 0);
    s_axi_rvalid  : OUT std_logic;
    s_axi_rready  : IN  std_logic
  );
END ENTITY axi_regs;

ARCHITECTURE rtl OF axi_regs IS

  TYPE t_registers IS ARRAY (0 TO G_REGISTERS - 1) OF std_logic_vector(31 DOWNTO 0);

  SIGNAL reg_file_r : t_registers;

  -- Word index, so the two low address bits are dropped.
  SIGNAL wr_index : natural;
  SIGNAL rd_index : natural;

  -- Internal drivers: the handshake reads back what it drives,
  -- and reading an out port is illegal before VHDL-2008.
  SIGNAL s_axi_awready_r : std_logic;
  SIGNAL s_axi_wready_r  : std_logic;
  SIGNAL s_axi_bresp_r   : std_logic_vector(1 DOWNTO 0);
  SIGNAL s_axi_bvalid_r  : std_logic;
  SIGNAL s_axi_arready_r : std_logic;
  SIGNAL s_axi_rdata_r   : std_logic_vector(31 DOWNTO 0);
  SIGNAL s_axi_rresp_r   : std_logic_vector(1 DOWNTO 0);
  SIGNAL s_axi_rvalid_r  : std_logic;

BEGIN

  wr_index <= TO_INTEGER(UNSIGNED(s_axi_awaddr(G_ADDR_WIDTH - 1 DOWNTO 2)));
  rd_index <= TO_INTEGER(UNSIGNED(s_axi_araddr(G_ADDR_WIDTH - 1 DOWNTO 2)));

  p_write : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        s_axi_awready_r <= '0';
        s_axi_wready_r <= '0';
        s_axi_bvalid_r <= '0';
        s_axi_bresp_r <= "00";
        reg_file_r <= (OTHERS => (OTHERS => '0'));
      ELSE
        -- READY is a single cycle pulse.
        s_axi_awready_r <= '0';
        s_axi_wready_r <= '0';

        IF s_axi_bvalid_r = '1' AND s_axi_bready = '1' THEN
          s_axi_bvalid_r <= '0';
        END IF;

        -- Both channels must be valid, so a response is never
        -- issued before the data arrives, and no new response is
        -- started while an earlier one is outstanding.
        IF s_axi_awvalid = '1' AND s_axi_wvalid = '1'
            AND s_axi_awready_r = '0' AND s_axi_wready_r = '0'
            AND (s_axi_bvalid_r = '0' OR s_axi_bready = '1') THEN
          s_axi_awready_r <= '1';
          s_axi_wready_r <= '1';

          IF wr_index < G_REGISTERS THEN
            -- Byte strobes: ignoring them corrupts a
            -- read-modify-write from software.
            FOR byte IN 0 TO 3 LOOP
              IF s_axi_wstrb(byte) = '1' THEN
                reg_file_r(wr_index)(byte * 8 + 7 DOWNTO byte * 8) <=
                  s_axi_wdata(byte * 8 + 7 DOWNTO byte * 8);
              END IF;
            END LOOP;
            s_axi_bresp_r <= "00";
          ELSE
            -- Outside the register file: DECERR rather than a
            -- silent alias, so a bad address is visible.
            s_axi_bresp_r <= "11";
          END IF;

          s_axi_bvalid_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_write;

  p_read : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        s_axi_arready_r <= '0';
        s_axi_rvalid_r <= '0';
        s_axi_rresp_r <= "00";
        s_axi_rdata_r <= (OTHERS => '0');
      ELSE
        s_axi_arready_r <= '0';

        IF s_axi_rvalid_r = '1' AND s_axi_rready = '1' THEN
          s_axi_rvalid_r <= '0';
        END IF;

        IF s_axi_arvalid = '1' AND s_axi_arready_r = '0'
            AND (s_axi_rvalid_r = '0' OR s_axi_rready = '1') THEN
          s_axi_arready_r <= '1';

          IF rd_index < G_REGISTERS THEN
            s_axi_rdata_r <= reg_file_r(rd_index);
            s_axi_rresp_r <= "00";
          ELSE
            s_axi_rdata_r <= (OTHERS => '0');
            s_axi_rresp_r <= "11";
          END IF;

          s_axi_rvalid_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_read;

  s_axi_awready <= s_axi_awready_r;
  s_axi_wready  <= s_axi_wready_r;
  s_axi_bresp   <= s_axi_bresp_r;
  s_axi_bvalid  <= s_axi_bvalid_r;
  s_axi_arready <= s_axi_arready_r;
  s_axi_rdata   <= s_axi_rdata_r;
  s_axi_rresp   <= s_axi_rresp_r;
  s_axi_rvalid  <= s_axi_rvalid_r;

END ARCHITECTURE rtl;
