-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axi4lite_slave   variant: default   case: prefix_ctrl

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity axi_regs is
  generic (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 4
  );
  port (
    clk          : in  std_logic;
    rst_n        : in  std_logic;
    ctrl_awaddr  : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    ctrl_awvalid : in  std_logic;
    ctrl_awready : out std_logic;
    ctrl_wdata   : in  std_logic_vector(31 downto 0);
    ctrl_wstrb   : in  std_logic_vector(3 downto 0);
    ctrl_wvalid  : in  std_logic;
    ctrl_wready  : out std_logic;
    ctrl_bresp   : out std_logic_vector(1 downto 0);
    ctrl_bvalid  : out std_logic;
    ctrl_bready  : in  std_logic;
    ctrl_araddr  : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    ctrl_arvalid : in  std_logic;
    ctrl_arready : out std_logic;
    ctrl_rdata   : out std_logic_vector(31 downto 0);
    ctrl_rresp   : out std_logic_vector(1 downto 0);
    ctrl_rvalid  : out std_logic;
    ctrl_rready  : in  std_logic
  );
end entity axi_regs;

architecture rtl of axi_regs is

  type t_registers is array (0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal reg_file_r : t_registers;

  -- Word index, so the two low address bits are dropped.
  signal wr_index : natural;
  signal rd_index : natural;

  -- Internal drivers: the handshake reads back what it drives,
  -- and reading an out port is illegal before VHDL-2008.
  signal ctrl_awready_r : std_logic;
  signal ctrl_wready_r  : std_logic;
  signal ctrl_bresp_r   : std_logic_vector(1 downto 0);
  signal ctrl_bvalid_r  : std_logic;
  signal ctrl_arready_r : std_logic;
  signal ctrl_rdata_r   : std_logic_vector(31 downto 0);
  signal ctrl_rresp_r   : std_logic_vector(1 downto 0);
  signal ctrl_rvalid_r  : std_logic;

begin

  wr_index <= to_integer(unsigned(ctrl_awaddr(G_ADDR_WIDTH - 1 downto 2)));
  rd_index <= to_integer(unsigned(ctrl_araddr(G_ADDR_WIDTH - 1 downto 2)));

  p_write : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      ctrl_awready_r <= '0';
      ctrl_wready_r <= '0';
      ctrl_bvalid_r <= '0';
      ctrl_bresp_r <= "00";
      reg_file_r <= (others => (others => '0'));
    elsif rising_edge(clk) then
      -- READY is a single cycle pulse.
      ctrl_awready_r <= '0';
      ctrl_wready_r <= '0';

      if ctrl_bvalid_r = '1' and ctrl_bready = '1' then
        ctrl_bvalid_r <= '0';
      end if;

      -- Both channels must be valid, so a response is never
      -- issued before the data arrives, and no new response is
      -- started while an earlier one is outstanding.
      if ctrl_awvalid = '1' and ctrl_wvalid = '1'
          and ctrl_awready_r = '0' and ctrl_wready_r = '0'
          and (ctrl_bvalid_r = '0' or ctrl_bready = '1') then
        ctrl_awready_r <= '1';
        ctrl_wready_r <= '1';

        if wr_index < G_REGISTERS then
          -- Byte strobes: ignoring them corrupts a
          -- read-modify-write from software.
          for byte in 0 to 3 loop
            if ctrl_wstrb(byte) = '1' then
              reg_file_r(wr_index)(byte * 8 + 7 downto byte * 8) <=
                ctrl_wdata(byte * 8 + 7 downto byte * 8);
            end if;
          end loop;
          ctrl_bresp_r <= "00";
        else
          -- Outside the register file: DECERR rather than a
          -- silent alias, so a bad address is visible.
          ctrl_bresp_r <= "11";
        end if;

        ctrl_bvalid_r <= '1';
      end if;
    end if;
  end process p_write;

  p_read : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      ctrl_arready_r <= '0';
      ctrl_rvalid_r <= '0';
      ctrl_rresp_r <= "00";
      ctrl_rdata_r <= (others => '0');
    elsif rising_edge(clk) then
      ctrl_arready_r <= '0';

      if ctrl_rvalid_r = '1' and ctrl_rready = '1' then
        ctrl_rvalid_r <= '0';
      end if;

      if ctrl_arvalid = '1' and ctrl_arready_r = '0'
          and (ctrl_rvalid_r = '0' or ctrl_rready = '1') then
        ctrl_arready_r <= '1';

        if rd_index < G_REGISTERS then
          ctrl_rdata_r <= reg_file_r(rd_index);
          ctrl_rresp_r <= "00";
        else
          ctrl_rdata_r <= (others => '0');
          ctrl_rresp_r <= "11";
        end if;

        ctrl_rvalid_r <= '1';
      end if;
    end if;
  end process p_read;

  ctrl_awready <= ctrl_awready_r;
  ctrl_wready  <= ctrl_wready_r;
  ctrl_bresp   <= ctrl_bresp_r;
  ctrl_bvalid  <= ctrl_bvalid_r;
  ctrl_arready <= ctrl_arready_r;
  ctrl_rdata   <= ctrl_rdata_r;
  ctrl_rresp   <= ctrl_rresp_r;
  ctrl_rvalid  <= ctrl_rvalid_r;

end architecture rtl;
