-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axi4lite_slave   variant: upper_sync_high   case: prefix_ctrl

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY axi_regs IS
  GENERIC (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 4
  );
  PORT (
    clk          : IN  std_logic;
    rst          : IN  std_logic;
    ctrl_awaddr  : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    ctrl_awvalid : IN  std_logic;
    ctrl_awready : OUT std_logic;
    ctrl_wdata   : IN  std_logic_vector(31 DOWNTO 0);
    ctrl_wstrb   : IN  std_logic_vector(3 DOWNTO 0);
    ctrl_wvalid  : IN  std_logic;
    ctrl_wready  : OUT std_logic;
    ctrl_bresp   : OUT std_logic_vector(1 DOWNTO 0);
    ctrl_bvalid  : OUT std_logic;
    ctrl_bready  : IN  std_logic;
    ctrl_araddr  : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    ctrl_arvalid : IN  std_logic;
    ctrl_arready : OUT std_logic;
    ctrl_rdata   : OUT std_logic_vector(31 DOWNTO 0);
    ctrl_rresp   : OUT std_logic_vector(1 DOWNTO 0);
    ctrl_rvalid  : OUT std_logic;
    ctrl_rready  : IN  std_logic
  );
END ENTITY axi_regs;

ARCHITECTURE rtl OF axi_regs IS

  TYPE t_registers IS ARRAY (0 TO G_REGISTERS - 1) OF std_logic_vector(31 DOWNTO 0);

  SIGNAL reg_file_r : t_registers;

  -- Word index, so the two low address bits are dropped.
  SIGNAL wr_index : natural;
  SIGNAL rd_index : natural;

  -- Internal drivers: the handshake reads back what it drives,
  -- and reading an out port is illegal before VHDL-2008.
  SIGNAL ctrl_awready_r : std_logic;
  SIGNAL ctrl_wready_r  : std_logic;
  SIGNAL ctrl_bresp_r   : std_logic_vector(1 DOWNTO 0);
  SIGNAL ctrl_bvalid_r  : std_logic;
  SIGNAL ctrl_arready_r : std_logic;
  SIGNAL ctrl_rdata_r   : std_logic_vector(31 DOWNTO 0);
  SIGNAL ctrl_rresp_r   : std_logic_vector(1 DOWNTO 0);
  SIGNAL ctrl_rvalid_r  : std_logic;

BEGIN

  wr_index <= TO_INTEGER(UNSIGNED(ctrl_awaddr(G_ADDR_WIDTH - 1 DOWNTO 2)));
  rd_index <= TO_INTEGER(UNSIGNED(ctrl_araddr(G_ADDR_WIDTH - 1 DOWNTO 2)));

  p_write : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        ctrl_awready_r <= '0';
        ctrl_wready_r <= '0';
        ctrl_bvalid_r <= '0';
        ctrl_bresp_r <= "00";
        reg_file_r <= (OTHERS => (OTHERS => '0'));
      ELSE
        -- READY is a single cycle pulse.
        ctrl_awready_r <= '0';
        ctrl_wready_r <= '0';

        IF ctrl_bvalid_r = '1' AND ctrl_bready = '1' THEN
          ctrl_bvalid_r <= '0';
        END IF;

        -- Both channels must be valid, so a response is never
        -- issued before the data arrives, and no new response is
        -- started while an earlier one is outstanding.
        IF ctrl_awvalid = '1' AND ctrl_wvalid = '1'
            AND ctrl_awready_r = '0' AND ctrl_wready_r = '0'
            AND (ctrl_bvalid_r = '0' OR ctrl_bready = '1') THEN
          ctrl_awready_r <= '1';
          ctrl_wready_r <= '1';

          IF wr_index < G_REGISTERS THEN
            -- Byte strobes: ignoring them corrupts a
            -- read-modify-write from software.
            FOR byte IN 0 TO 3 LOOP
              IF ctrl_wstrb(byte) = '1' THEN
                reg_file_r(wr_index)(byte * 8 + 7 DOWNTO byte * 8) <=
                  ctrl_wdata(byte * 8 + 7 DOWNTO byte * 8);
              END IF;
            END LOOP;
            ctrl_bresp_r <= "00";
          ELSE
            -- Outside the register file: DECERR rather than a
            -- silent alias, so a bad address is visible.
            ctrl_bresp_r <= "11";
          END IF;

          ctrl_bvalid_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_write;

  p_read : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        ctrl_arready_r <= '0';
        ctrl_rvalid_r <= '0';
        ctrl_rresp_r <= "00";
        ctrl_rdata_r <= (OTHERS => '0');
      ELSE
        ctrl_arready_r <= '0';

        IF ctrl_rvalid_r = '1' AND ctrl_rready = '1' THEN
          ctrl_rvalid_r <= '0';
        END IF;

        IF ctrl_arvalid = '1' AND ctrl_arready_r = '0'
            AND (ctrl_rvalid_r = '0' OR ctrl_rready = '1') THEN
          ctrl_arready_r <= '1';

          IF rd_index < G_REGISTERS THEN
            ctrl_rdata_r <= reg_file_r(rd_index);
            ctrl_rresp_r <= "00";
          ELSE
            ctrl_rdata_r <= (OTHERS => '0');
            ctrl_rresp_r <= "11";
          END IF;

          ctrl_rvalid_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_read;

  ctrl_awready <= ctrl_awready_r;
  ctrl_wready  <= ctrl_wready_r;
  ctrl_bresp   <= ctrl_bresp_r;
  ctrl_bvalid  <= ctrl_bvalid_r;
  ctrl_arready <= ctrl_arready_r;
  ctrl_rdata   <= ctrl_rdata_r;
  ctrl_rresp   <= ctrl_rresp_r;
  ctrl_rvalid  <= ctrl_rvalid_r;

END ARCHITECTURE rtl;
