-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axi4lite_slave   variant: amd   case: registers_1

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity axi_regs is
  generic (
    G_REGISTERS : positive := 1;
    G_ADDR_WIDTH : positive := 3
  );
  port (
    clk           : in  std_logic;
    rst_n         : in  std_logic;
    s_axi_awaddr  : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    s_axi_awvalid : in  std_logic;
    s_axi_awready : out std_logic;
    s_axi_wdata   : in  std_logic_vector(31 downto 0);
    s_axi_wstrb   : in  std_logic_vector(3 downto 0);
    s_axi_wvalid  : in  std_logic;
    s_axi_wready  : out std_logic;
    s_axi_bresp   : out std_logic_vector(1 downto 0);
    s_axi_bvalid  : out std_logic;
    s_axi_bready  : in  std_logic;
    s_axi_araddr  : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    s_axi_arvalid : in  std_logic;
    s_axi_arready : out std_logic;
    s_axi_rdata   : out std_logic_vector(31 downto 0);
    s_axi_rresp   : out std_logic_vector(1 downto 0);
    s_axi_rvalid  : out std_logic;
    s_axi_rready  : in  std_logic
  );
end entity axi_regs;

architecture rtl of axi_regs is

  type t_registers is array (0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal reg_file_r : t_registers;

  -- Word index, so the two low address bits are dropped.
  signal wr_index : natural;
  signal rd_index : natural;

  -- Internal drivers: the handshake reads back what it drives,
  -- and reading an out port is illegal before VHDL-2008.
  signal s_axi_awready_r : std_logic;
  signal s_axi_wready_r  : std_logic;
  signal s_axi_bresp_r   : std_logic_vector(1 downto 0);
  signal s_axi_bvalid_r  : std_logic;
  signal s_axi_arready_r : std_logic;
  signal s_axi_rdata_r   : std_logic_vector(31 downto 0);
  signal s_axi_rresp_r   : std_logic_vector(1 downto 0);
  signal s_axi_rvalid_r  : std_logic;

begin

  wr_index <= to_integer(unsigned(s_axi_awaddr(G_ADDR_WIDTH - 1 downto 2)));
  rd_index <= to_integer(unsigned(s_axi_araddr(G_ADDR_WIDTH - 1 downto 2)));

  p_write : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      s_axi_awready_r <= '0';
      s_axi_wready_r <= '0';
      s_axi_bvalid_r <= '0';
      s_axi_bresp_r <= "00";
      reg_file_r <= (others => (others => '0'));
    elsif rising_edge(clk) then
      -- READY is a single cycle pulse.
      s_axi_awready_r <= '0';
      s_axi_wready_r <= '0';

      if s_axi_bvalid_r = '1' and s_axi_bready = '1' then
        s_axi_bvalid_r <= '0';
      end if;

      -- Both channels must be valid, so a response is never
      -- issued before the data arrives, and no new response is
      -- started while an earlier one is outstanding.
      if s_axi_awvalid = '1' and s_axi_wvalid = '1'
          and s_axi_awready_r = '0' and s_axi_wready_r = '0'
          and (s_axi_bvalid_r = '0' or s_axi_bready = '1') then
        s_axi_awready_r <= '1';
        s_axi_wready_r <= '1';

        if wr_index < G_REGISTERS then
          -- Byte strobes: ignoring them corrupts a
          -- read-modify-write from software.
          for byte in 0 to 3 loop
            if s_axi_wstrb(byte) = '1' then
              reg_file_r(wr_index)(byte * 8 + 7 downto byte * 8) <=
                s_axi_wdata(byte * 8 + 7 downto byte * 8);
            end if;
          end loop;
          s_axi_bresp_r <= "00";
        else
          -- Outside the register file: DECERR rather than a
          -- silent alias, so a bad address is visible.
          s_axi_bresp_r <= "11";
        end if;

        s_axi_bvalid_r <= '1';
      end if;
    end if;
  end process p_write;

  p_read : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      s_axi_arready_r <= '0';
      s_axi_rvalid_r <= '0';
      s_axi_rresp_r <= "00";
      s_axi_rdata_r <= (others => '0');
    elsif rising_edge(clk) then
      s_axi_arready_r <= '0';

      if s_axi_rvalid_r = '1' and s_axi_rready = '1' then
        s_axi_rvalid_r <= '0';
      end if;

      if s_axi_arvalid = '1' and s_axi_arready_r = '0'
          and (s_axi_rvalid_r = '0' or s_axi_rready = '1') then
        s_axi_arready_r <= '1';

        if rd_index < G_REGISTERS then
          s_axi_rdata_r <= reg_file_r(rd_index);
          s_axi_rresp_r <= "00";
        else
          s_axi_rdata_r <= (others => '0');
          s_axi_rresp_r <= "11";
        end if;

        s_axi_rvalid_r <= '1';
      end if;
    end if;
  end process p_read;

  s_axi_awready <= s_axi_awready_r;
  s_axi_wready  <= s_axi_wready_r;
  s_axi_bresp   <= s_axi_bresp_r;
  s_axi_bvalid  <= s_axi_bvalid_r;
  s_axi_arready <= s_axi_arready_r;
  s_axi_rdata   <= s_axi_rdata_r;
  s_axi_rresp   <= s_axi_rresp_r;
  s_axi_rvalid  <= s_axi_rvalid_r;

end architecture rtl;
