-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axis_skid   variant: upper_sync_high   case: name_gold_name

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

ENTITY gold_name IS
  GENERIC (
    G_TDATA_WIDTH : positive := 32
  );
  PORT (
    clk      : IN  std_logic;
    rst      : IN  std_logic;
    s_tdata  : IN  std_logic_vector(G_TDATA_WIDTH - 1 DOWNTO 0);
    s_tlast  : IN  std_logic;
    s_tvalid : IN  std_logic;
    s_tready : OUT std_logic;
    m_tdata  : OUT std_logic_vector(G_TDATA_WIDTH - 1 DOWNTO 0);
    m_tlast  : OUT std_logic;
    m_tvalid : OUT std_logic;
    m_tready : IN  std_logic
  );
END ENTITY gold_name;

ARCHITECTURE rtl OF gold_name IS

  -- Output register.
  SIGNAL m_data_r : std_logic_vector(G_TDATA_WIDTH - 1 DOWNTO 0);
  SIGNAL m_last_r : std_logic;
  SIGNAL m_valid_r : std_logic := '0';

  -- Skid register: holds the word accepted in the cycle the
  -- downstream stall arrived, which would otherwise be lost.
  SIGNAL skid_data_r : std_logic_vector(G_TDATA_WIDTH - 1 DOWNTO 0);
  SIGNAL skid_last_r : std_logic;
  SIGNAL skid_full_r : std_logic := '0';

BEGIN

  -- Accept while the skid register is empty.
  s_tready <= NOT skid_full_r;

  p_skid : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        m_valid_r <= '0';
        skid_full_r <= '0';
      ELSE
        -- The output register is free when it is empty, or when
        -- downstream took the word this cycle.
        IF m_valid_r = '0' OR m_tready = '1' THEN
          IF skid_full_r = '1' THEN
            m_data_r <= skid_data_r;
            m_last_r <= skid_last_r;
            m_valid_r <= '1';
            skid_full_r <= '0';
          ELSIF s_tvalid = '1' AND skid_full_r = '0' THEN
            m_data_r <= s_tdata;
            m_last_r <= s_tlast;
            m_valid_r <= '1';
          ELSE
            m_valid_r <= '0';
          END IF;
        ELSIF s_tvalid = '1' AND skid_full_r = '0' THEN
          -- Downstream is stalled and the output is occupied, so
          -- this word goes to the skid register rather than away.
          skid_data_r <= s_tdata;
          skid_last_r <= s_tlast;
          skid_full_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_skid;

  m_tdata  <= m_data_r;
  m_tlast  <= m_last_r;
  m_tvalid <= m_valid_r;

END ARCHITECTURE rtl;
