-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axis_skid   variant: no_reset   case: width_1

library ieee;
  use ieee.std_logic_1164.all;

entity axis_skid is
  generic (
    G_TDATA_WIDTH : positive := 1
  );
  port (
    clk      : in  std_logic;
    s_tdata  : in  std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
    s_tlast  : in  std_logic;
    s_tvalid : in  std_logic;
    s_tready : out std_logic;
    m_tdata  : out std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
    m_tlast  : out std_logic;
    m_tvalid : out std_logic;
    m_tready : in  std_logic
  );
end entity axis_skid;

architecture rtl of axis_skid is

  -- Output register.
  signal m_data_r : std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
  signal m_last_r : std_logic;
  signal m_valid_r : std_logic := '0';

  -- Skid register: holds the word accepted in the cycle the
  -- downstream stall arrived, which would otherwise be lost.
  signal skid_data_r : std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
  signal skid_last_r : std_logic;
  signal skid_full_r : std_logic := '0';

begin

  -- Accept while the skid register is empty.
  s_tready <= not skid_full_r;

  p_skid : process (clk) is
  begin
    if rising_edge(clk) then
      -- The output register is free when it is empty, or when
      -- downstream took the word this cycle.
      if m_valid_r = '0' or m_tready = '1' then
        if skid_full_r = '1' then
          m_data_r <= skid_data_r;
          m_last_r <= skid_last_r;
          m_valid_r <= '1';
          skid_full_r <= '0';
        elsif s_tvalid = '1' and skid_full_r = '0' then
          m_data_r <= s_tdata;
          m_last_r <= s_tlast;
          m_valid_r <= '1';
        else
          m_valid_r <= '0';
        end if;
      elsif s_tvalid = '1' and skid_full_r = '0' then
        -- Downstream is stalled and the output is occupied, so
        -- this word goes to the skid register rather than away.
        skid_data_r <= s_tdata;
        skid_last_r <= s_tlast;
        skid_full_r <= '1';
      end if;
    end if;
  end process p_skid;

  m_tdata  <= m_data_r;
  m_tlast  <= m_last_r;
  m_tvalid <= m_valid_r;

end architecture rtl;
