-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: axis_skid   variant: long_names   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;

entity gold_name is
  generic (
    G_TDATA_WIDTH : positive := 32
  );
  port (
    axi_aclk    : in  std_logic;
    axi_aresetn : in  std_logic;
    s_tdata     : in  std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
    s_tlast     : in  std_logic;
    s_tvalid    : in  std_logic;
    s_tready    : out std_logic;
    m_tdata     : out std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
    m_tlast     : out std_logic;
    m_tvalid    : out std_logic;
    m_tready    : in  std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

  -- Output register.
  signal s_m_data_r : std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
  signal s_m_last_r : std_logic;
  signal s_m_valid_r : std_logic := '0';

  -- Skid register: holds the word accepted in the cycle the
  -- downstream stall arrived, which would otherwise be lost.
  signal s_skid_data_r : std_logic_vector(G_TDATA_WIDTH - 1 downto 0);
  signal s_skid_last_r : std_logic;
  signal s_skid_full_r : std_logic := '0';

begin

  -- Accept while the skid register is empty.
  s_tready <= not s_skid_full_r;

  p_skid : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_m_valid_r <= '0';
      s_skid_full_r <= '0';
    elsif rising_edge(axi_aclk) then
      -- The output register is free when it is empty, or when
      -- downstream took the word this cycle.
      if s_m_valid_r = '0' or m_tready = '1' then
        if s_skid_full_r = '1' then
          s_m_data_r <= s_skid_data_r;
          s_m_last_r <= s_skid_last_r;
          s_m_valid_r <= '1';
          s_skid_full_r <= '0';
        elsif s_tvalid = '1' and s_skid_full_r = '0' then
          s_m_data_r <= s_tdata;
          s_m_last_r <= s_tlast;
          s_m_valid_r <= '1';
        else
          s_m_valid_r <= '0';
        end if;
      elsif s_tvalid = '1' and s_skid_full_r = '0' then
        -- Downstream is stalled and the output is occupied, so
        -- this word goes to the skid register rather than away.
        s_skid_data_r <= s_tdata;
        s_skid_last_r <= s_tlast;
        s_skid_full_r <= '1';
      end if;
    end if;
  end process p_skid;

  m_tdata  <= s_m_data_r;
  m_tlast  <= s_m_last_r;
  m_tvalid <= s_m_valid_r;

end architecture rtl;
