-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: bit_sync   variant: long_names   case: stages_8

library ieee;
  use ieee.std_logic_1164.all;

-- Single-bit synchroniser.
--
-- Valid for one bit at a time. A bus, or several bits that must
-- stay mutually consistent, needs a handshake or a gray coded
-- pointer instead: each bit here settles independently.
--
-- Constrain the source register with set_max_delay -datapath_only
-- so the crossing is not timed as a normal path.
entity bit_sync is
  generic (
    G_STAGES : positive := 8;
    G_INIT   : std_logic := '0'
  );
  port (
    axi_aclk    : in  std_logic;
    axi_aresetn : in  std_logic;
    s_d_i       : in  std_logic;
    s_q_o       : out std_logic
  );
end entity bit_sync;

architecture rtl of bit_sync is

  signal s_sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => G_INIT);

begin

  assert G_STAGES >= 2
    report "bit_sync: needs at least two stages"
    severity failure;

  p_sync : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_sync_r <= (others => G_INIT);
    elsif rising_edge(axi_aclk) then
      s_sync_r <= s_sync_r(s_sync_r'high - 1 downto 0) & s_d_i;
    end if;
  end process p_sync;

  s_q_o <= s_sync_r(s_sync_r'high);

end architecture rtl;
