-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: bit_sync   variant: vhdl93   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;

-- Single-bit synchroniser.
--
-- Valid for one bit at a time. A bus, or several bits that must
-- stay mutually consistent, needs a handshake or a gray coded
-- pointer instead: each bit here settles independently.
--
-- Constrain the source register with set_max_delay -datapath_only
-- so the crossing is not timed as a normal path.
entity gold_name is
  generic (
    G_STAGES : positive := 2;
    G_INIT   : std_logic := '0'
  );
  port (
    clk   : in  std_logic;
    rst_n : in  std_logic;
    d_i   : in  std_logic;
    q_o   : out std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

  signal sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => G_INIT);

begin

  assert G_STAGES >= 2
    report "gold_name: needs at least two stages"
    severity failure;

  p_sync : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      sync_r <= (others => G_INIT);
    elsif rising_edge(clk) then
      sync_r <= sync_r(sync_r'high - 1 downto 0) & d_i;
    end if;
  end process p_sync;

  q_o <= sync_r(sync_r'high);

end architecture rtl;
