-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: bit_sync   variant: upper_sync_high   case: defaults

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

-- Single-bit synchroniser.
--
-- Valid for one bit at a time. A bus, or several bits that must
-- stay mutually consistent, needs a handshake or a gray coded
-- pointer instead: each bit here settles independently.
--
-- Constrain the source register with set_max_delay -datapath_only
-- so the crossing is not timed as a normal path.
ENTITY bit_sync IS
  GENERIC (
    G_STAGES : positive := 2;
    G_INIT   : std_logic := '0'
  );
  PORT (
    clk : IN  std_logic;
    rst : IN  std_logic;
    d_i : IN  std_logic;
    q_o : OUT std_logic
  );
END ENTITY bit_sync;

ARCHITECTURE rtl OF bit_sync IS

  SIGNAL sync_r : std_logic_vector(G_STAGES - 1 DOWNTO 0) := (OTHERS => G_INIT);

BEGIN

  ASSERT G_STAGES >= 2
    REPORT "bit_sync: needs at least two stages"
    SEVERITY FAILURE;

  p_sync : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        sync_r <= (OTHERS => G_INIT);
      ELSE
        sync_r <= sync_r(sync_r'high - 1 DOWNTO 0) & d_i;
      END IF;
    END IF;
  END PROCESS p_sync;

  q_o <= sync_r(sync_r'high);

END ARCHITECTURE rtl;
