-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: cdc_handshake   variant: vhdl93   case: defaults

library ieee;
  use ieee.std_logic_1164.all;

-- Multi-bit crossing by handshake.
--
-- Only the request and acknowledge bits cross through
-- synchronisers. The payload is never synchronised: it is held
-- stable for the whole crossing instead, which is what makes it
-- safe to sample directly.
--
-- Constrain both crossings with set_max_delay -datapath_only,
-- and the payload path with a bus-skew constraint.
entity cdc_handshake is
  generic (
    G_WIDTH  : positive := 16;
    G_STAGES : positive := 2
  );
  port (
    src_clk     : in  std_logic;
    src_rst_n   : in  std_logic;
    src_valid_i : in  std_logic;
    src_data_i  : in  std_logic_vector(G_WIDTH - 1 downto 0);
    src_ready_o : out std_logic;
    dst_clk     : in  std_logic;
    dst_rst_n   : in  std_logic;
    dst_valid_o : out std_logic;
    dst_data_o  : out std_logic_vector(G_WIDTH - 1 downto 0)
  );
end entity cdc_handshake;

architecture rtl of cdc_handshake is

  -- Source domain.
  signal payload_r : std_logic_vector(G_WIDTH - 1 downto 0) := (others => '0');
  signal req_r : std_logic := '0';
  signal ack_sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => '0');

  -- Destination domain.
  signal ack_r : std_logic := '0';
  signal req_sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => '0');

begin

  -- The payload changes only while the request is idle, so it is
  -- stable for the whole crossing and needs no synchroniser.
  p_source : process (src_clk, src_rst_n) is
  begin
    if src_rst_n = '0' then
      req_r <= '0';
      ack_sync_r <= (others => '0');
      payload_r <= (others => '0');
    elsif rising_edge(src_clk) then
      ack_sync_r <= ack_sync_r(ack_sync_r'high - 1 downto 0) & ack_r;

      if req_r = '0' then
        if src_valid_i = '1' and ack_sync_r(ack_sync_r'high) = '0' then
          payload_r <= src_data_i;
          req_r <= '1';
        end if;
      elsif ack_sync_r(ack_sync_r'high) = '1' then
        req_r <= '0';
      end if;
    end if;
  end process p_source;

  src_ready_o <= '1' when req_r = '0' and ack_sync_r(ack_sync_r'high) = '0' else '0';

  p_dest : process (dst_clk, dst_rst_n) is
  begin
    if dst_rst_n = '0' then
      ack_r <= '0';
      req_sync_r <= (others => '0');
      dst_valid_o <= '0';
      dst_data_o <= (others => '0');
    elsif rising_edge(dst_clk) then
      req_sync_r <= req_sync_r(req_sync_r'high - 1 downto 0) & req_r;
      dst_valid_o <= '0';

      -- The payload has been stable for at least the crossing
      -- delay by now, so it is sampled directly.
      if req_sync_r(req_sync_r'high) = '1' and ack_r = '0' then
        dst_data_o <= payload_r;
        dst_valid_o <= '1';
        ack_r <= '1';
      elsif req_sync_r(req_sync_r'high) = '0' then
        ack_r <= '0';
      end if;
    end if;
  end process p_dest;

end architecture rtl;
