-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: cdc_handshake   variant: long_names   case: width_4096

library ieee;
  use ieee.std_logic_1164.all;

-- Multi-bit crossing by handshake.
--
-- Only the request and acknowledge bits cross through
-- synchronisers. The payload is never synchronised: it is held
-- stable for the whole crossing instead, which is what makes it
-- safe to sample directly.
--
-- Constrain both crossings with set_max_delay -datapath_only,
-- and the payload path with a bus-skew constraint.
entity cdc_handshake is
  generic (
    G_WIDTH  : positive := 4096;
    G_STAGES : positive := 2
  );
  port (
    src_axi_aclk    : in  std_logic;
    src_axi_aresetn : in  std_logic;
    s_src_valid_i   : in  std_logic;
    s_src_data_i    : in  std_logic_vector(G_WIDTH - 1 downto 0);
    s_src_ready_o   : out std_logic;
    dst_axi_aclk    : in  std_logic;
    dst_axi_aresetn : in  std_logic;
    s_dst_valid_o   : out std_logic;
    s_dst_data_o    : out std_logic_vector(G_WIDTH - 1 downto 0)
  );
end entity cdc_handshake;

architecture rtl of cdc_handshake is

  -- Source domain.
  signal s_payload_r : std_logic_vector(G_WIDTH - 1 downto 0) := (others => '0');
  signal s_req_r : std_logic := '0';
  signal s_ack_sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => '0');

  -- Destination domain.
  signal s_ack_r : std_logic := '0';
  signal s_req_sync_r : std_logic_vector(G_STAGES - 1 downto 0) := (others => '0');

begin

  -- The payload changes only while the request is idle, so it is
  -- stable for the whole crossing and needs no synchroniser.
  p_source : process (src_axi_aclk, src_axi_aresetn) is
  begin
    if src_axi_aresetn = '0' then
      s_req_r <= '0';
      s_ack_sync_r <= (others => '0');
      s_payload_r <= (others => '0');
    elsif rising_edge(src_axi_aclk) then
      s_ack_sync_r <= s_ack_sync_r(s_ack_sync_r'high - 1 downto 0) & s_ack_r;

      if s_req_r = '0' then
        if s_src_valid_i = '1' and s_ack_sync_r(s_ack_sync_r'high) = '0' then
          s_payload_r <= s_src_data_i;
          s_req_r <= '1';
        end if;
      elsif s_ack_sync_r(s_ack_sync_r'high) = '1' then
        s_req_r <= '0';
      end if;
    end if;
  end process p_source;

  s_src_ready_o <= '1' when s_req_r = '0' and s_ack_sync_r(s_ack_sync_r'high) = '0' else '0';

  p_dest : process (dst_axi_aclk, dst_axi_aresetn) is
  begin
    if dst_axi_aresetn = '0' then
      s_ack_r <= '0';
      s_req_sync_r <= (others => '0');
      s_dst_valid_o <= '0';
      s_dst_data_o <= (others => '0');
    elsif rising_edge(dst_axi_aclk) then
      s_req_sync_r <= s_req_sync_r(s_req_sync_r'high - 1 downto 0) & s_req_r;
      s_dst_valid_o <= '0';

      -- The payload has been stable for at least the crossing
      -- delay by now, so it is sampled directly.
      if s_req_sync_r(s_req_sync_r'high) = '1' and s_ack_r = '0' then
        s_dst_data_o <= s_payload_r;
        s_dst_valid_o <= '1';
        s_ack_r <= '1';
      elsif s_req_sync_r(s_req_sync_r'high) = '0' then
        s_ack_r <= '0';
      end if;
    end if;
  end process p_dest;

end architecture rtl;
