-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: cdc_handshake   variant: upper_sync_high   case: defaults

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

-- Multi-bit crossing by handshake.
--
-- Only the request and acknowledge bits cross through
-- synchronisers. The payload is never synchronised: it is held
-- stable for the whole crossing instead, which is what makes it
-- safe to sample directly.
--
-- Constrain both crossings with set_max_delay -datapath_only,
-- and the payload path with a bus-skew constraint.
ENTITY cdc_handshake IS
  GENERIC (
    G_WIDTH  : positive := 16;
    G_STAGES : positive := 2
  );
  PORT (
    src_clk     : IN  std_logic;
    src_rst     : IN  std_logic;
    src_valid_i : IN  std_logic;
    src_data_i  : IN  std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    src_ready_o : OUT std_logic;
    dst_clk     : IN  std_logic;
    dst_rst     : IN  std_logic;
    dst_valid_o : OUT std_logic;
    dst_data_o  : OUT std_logic_vector(G_WIDTH - 1 DOWNTO 0)
  );
END ENTITY cdc_handshake;

ARCHITECTURE rtl OF cdc_handshake IS

  -- Source domain.
  SIGNAL payload_r : std_logic_vector(G_WIDTH - 1 DOWNTO 0) := (OTHERS => '0');
  SIGNAL req_r : std_logic := '0';
  SIGNAL ack_sync_r : std_logic_vector(G_STAGES - 1 DOWNTO 0) := (OTHERS => '0');

  -- Destination domain.
  SIGNAL ack_r : std_logic := '0';
  SIGNAL req_sync_r : std_logic_vector(G_STAGES - 1 DOWNTO 0) := (OTHERS => '0');

BEGIN

  -- The payload changes only while the request is idle, so it is
  -- stable for the whole crossing and needs no synchroniser.
  p_source : PROCESS (src_clk) IS
  BEGIN
    IF RISING_EDGE(src_clk) THEN
      IF src_rst = '1' THEN
        req_r <= '0';
        ack_sync_r <= (OTHERS => '0');
        payload_r <= (OTHERS => '0');
      ELSE
        ack_sync_r <= ack_sync_r(ack_sync_r'high - 1 DOWNTO 0) & ack_r;

        IF req_r = '0' THEN
          IF src_valid_i = '1' AND ack_sync_r(ack_sync_r'high) = '0' THEN
            payload_r <= src_data_i;
            req_r <= '1';
          END IF;
        ELSIF ack_sync_r(ack_sync_r'high) = '1' THEN
          req_r <= '0';
        END IF;
      END IF;
    END IF;
  END PROCESS p_source;

  src_ready_o <= '1' WHEN req_r = '0' AND ack_sync_r(ack_sync_r'high) = '0' ELSE '0';

  p_dest : PROCESS (dst_clk) IS
  BEGIN
    IF RISING_EDGE(dst_clk) THEN
      IF dst_rst = '1' THEN
        ack_r <= '0';
        req_sync_r <= (OTHERS => '0');
        dst_valid_o <= '0';
        dst_data_o <= (OTHERS => '0');
      ELSE
        req_sync_r <= req_sync_r(req_sync_r'high - 1 DOWNTO 0) & req_r;
        dst_valid_o <= '0';

        -- The payload has been stable for at least the crossing
        -- delay by now, so it is sampled directly.
        IF req_sync_r(req_sync_r'high) = '1' AND ack_r = '0' THEN
          dst_data_o <= payload_r;
          dst_valid_o <= '1';
          ack_r <= '1';
        ELSIF req_sync_r(req_sync_r'high) = '0' THEN
          ack_r <= '0';
        END IF;
      END IF;
    END IF;
  END PROCESS p_dest;

END ARCHITECTURE rtl;
