-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: counter   variant: vhdl93   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal count_en : std_logic;
  signal gold_sig_r : unsigned(7 downto 0) := (others => '0');

begin

  p_gold_sig : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      gold_sig_r <= (others => '0');
    elsif rising_edge(clk) then
      if count_en = '1' then
        gold_sig_r <= gold_sig_r + 1;
      end if;
    end if;
  end process p_gold_sig;

end architecture golden;
