-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: counter   variant: long_names   case: width_4096

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal s_count_en : std_logic;
  signal s_count_r : unsigned(4095 downto 0) := (others => '0');

begin

  p_count : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_count_r <= (others => '0');
    elsif rising_edge(axi_aclk) then
      if s_count_en = '1' then
        s_count_r <= s_count_r + 1;
      end if;
    end if;
  end process p_count;

end architecture golden;
