-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: counter   variant: upper_sync_high   case: at_end_saturate

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal count_en : std_logic;
  SIGNAL count_r : unsigned(7 DOWNTO 0) := (OTHERS => '0');

begin

  p_count : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        count_r <= (OTHERS => '0');
      ELSE
        IF count_en = '1' THEN
          IF count_r /= (count_r'range => '1') THEN
            count_r <= count_r + 1;
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS p_count;

end architecture golden;
