-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: counter   variant: upper_sync_high   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal count_en : std_logic;
  SIGNAL gold_sig_r : unsigned(7 DOWNTO 0) := (OTHERS => '0');

begin

  p_gold_sig : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        gold_sig_r <= (OTHERS => '0');
      ELSE
        IF count_en = '1' THEN
          gold_sig_r <= gold_sig_r + 1;
        END IF;
      END IF;
    END IF;
  END PROCESS p_gold_sig;

end architecture golden;
