-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: edge_detect   variant: long_names   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal gold_sig : std_logic;
  signal s_gold_sig_d_r : std_logic := '0';
  signal gold_sig_rising : std_logic;

begin

  p_gold_sig_edge : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_gold_sig_d_r <= '0';
    elsif rising_edge(axi_aclk) then
      s_gold_sig_d_r <= gold_sig;
    end if;
  end process p_gold_sig_edge;

  gold_sig_rising <= gold_sig and not s_gold_sig_d_r;

end architecture golden;
