-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: edge_detect   variant: upper_sync_high   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  SIGNAL flag : std_logic := '0';
  SIGNAL flag_d_r : std_logic := '0';
  SIGNAL flag_rising : std_logic;

begin

  p_flag_edge : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        flag_d_r <= '0';
      ELSE
        flag_d_r <= flag;
      END IF;
    END IF;
  END PROCESS p_flag_edge;

  flag_rising <= flag AND NOT flag_d_r;

end architecture golden;
