-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: edge_detect   variant: upper_sync_high   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  SIGNAL gold_sig : std_logic := '0';
  SIGNAL gold_sig_d_r : std_logic := '0';
  SIGNAL gold_sig_rising : std_logic;

begin

  p_gold_sig_edge : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        gold_sig_d_r <= '0';
      ELSE
        gold_sig_d_r <= gold_sig;
      END IF;
    END IF;
  END PROCESS p_gold_sig_edge;

  gold_sig_rising <= gold_sig AND NOT gold_sig_d_r;

end architecture golden;
