-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: edge_detect   variant: intel   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal flag : std_logic;
  signal flag_d_r : std_logic := '0';
  signal flag_rising : std_logic;

begin

  p_flag_edge : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      flag_d_r <= '0';
    elsif rising_edge(clk) then
      flag_d_r <= flag;
    end if;
  end process p_flag_edge;

  flag_rising <= flag and not flag_d_r;

end architecture golden;
