-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: edge_detect   variant: long_names   case: edge_both

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  signal flag : std_logic := '0';
  signal s_flag_d_r : std_logic := '0';
  signal flag_both : std_logic;

begin

  p_flag_edge : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_flag_d_r <= '0';
    elsif rising_edge(axi_aclk) then
      s_flag_d_r <= flag;
    end if;
  end process p_flag_edge;

  flag_both <= flag xor s_flag_d_r;

end architecture golden;
