-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: intel   case: arch_gold_arch

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity top is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity top;

architecture gold_arch of top is

begin

end architecture gold_arch;
