-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: long_names   case: generics_true

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity top is
  generic (
    G_WIDTH : positive := 8
  );
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity top;

architecture rtl of top is

begin

end architecture rtl;
