-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: no_reset   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity top is
  port (
    clk : in std_logic
  );
end entity top;

architecture rtl of top is

begin

end architecture rtl;
