-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: long_names   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity gold_name is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

begin

end architecture rtl;
