-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: upper_sync_high   case: defaults

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY top IS
  PORT (
    clk : IN std_logic;
    rst : IN std_logic
  );
END ENTITY top;

ARCHITECTURE rtl OF top IS

BEGIN

END ARCHITECTURE rtl;
