-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: upper_sync_high   case: name_gold_name

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY gold_name IS
  PORT (
    clk : IN std_logic;
    rst : IN std_logic
  );
END ENTITY gold_name;

ARCHITECTURE rtl OF gold_name IS

BEGIN

END ARCHITECTURE rtl;
