-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: entity   variant: vhdl93   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity gold_name is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

begin

end architecture rtl;
