-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_sync   variant: amd   case: defaults

library ieee;
  use ieee.std_logic_1164.all;

entity fifo_sync is
  generic (
    G_WIDTH : positive := 8;
    G_DEPTH : positive := 16
  );
  port (
    clk       : in  std_logic;
    rst_n     : in  std_logic;
    wr_en_i   : in  std_logic;
    wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    full_o    : out std_logic;
    rd_en_i   : in  std_logic;
    rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0);
    empty_o   : out std_logic
  );
end entity fifo_sync;

architecture rtl of fifo_sync is

  type t_memory is array (0 to G_DEPTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  signal memory_r : t_memory;

  signal wr_ptr_r : natural range 0 to G_DEPTH - 1 := 0;
  signal rd_ptr_r : natural range 0 to G_DEPTH - 1 := 0;
  signal count_r  : natural range 0 to G_DEPTH := 0;

  signal wr_go : boolean;
  signal rd_go : boolean;

begin

  -- A write to a full FIFO, or a read from an empty one, is
  -- ignored: a misbehaving master must not desynchronise it.
  wr_go <= wr_en_i = '1' and count_r < G_DEPTH;
  rd_go <= rd_en_i = '1' and count_r > 0;

  -- No reset here: a reset on every element prevents block RAM
  -- inference on most tools.
  p_memory : process (clk) is
  begin
    if rising_edge(clk) then
      if wr_go then
        memory_r(wr_ptr_r) <= wr_data_i;
      end if;
    end if;
  end process p_memory;

  p_pointers : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      wr_ptr_r <= 0;
      rd_ptr_r <= 0;
      count_r <= 0;
    elsif rising_edge(clk) then
      if wr_go then
        wr_ptr_r <= (wr_ptr_r + 1) mod G_DEPTH;
      end if;

      if rd_go then
        rd_ptr_r <= (rd_ptr_r + 1) mod G_DEPTH;
      end if;

      -- One update, so a simultaneous read and write is a no-op.
      if wr_go and not rd_go then
        count_r <= count_r + 1;
      elsif rd_go and not wr_go then
        count_r <= count_r - 1;
      end if;
    end if;
  end process p_pointers;

  -- Asynchronous read, so the first word is available without a
  -- strobe. Register it for block RAM, at a cycle of latency.
  rd_data_o <= memory_r(rd_ptr_r);

  full_o <= '1' when count_r = G_DEPTH else '0';
  empty_o <= '1' when count_r = 0 else '0';

end architecture rtl;
