-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_async   variant: vhdl93   case: width_4096

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Asynchronous FIFO.
--
-- The pointers are gray coded because they cross domains: a
-- binary pointer going from 0111 to 1000 changes four bits at
-- once, and a mid-transition sample could read any of sixteen
-- values. One bit changes per gray increment, so a sample is
-- always the old value or the new one.
--
-- Constrain both pointer crossings with set_max_delay
-- -datapath_only. The memory is not constrained: the write
-- pointer reaching the reader is what makes the data safe.
entity fifo_async is
  generic (
    G_WIDTH      : positive := 4096;
    G_ADDR_WIDTH : positive := 4;
    G_STAGES     : positive := 2
  );
  port (
    wr_clk    : in  std_logic;
    wr_rst_n  : in  std_logic;
    wr_en_i   : in  std_logic;
    wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    full_o    : out std_logic;
    rd_clk    : in  std_logic;
    rd_rst_n  : in  std_logic;
    rd_en_i   : in  std_logic;
    rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0);
    empty_o   : out std_logic
  );
end entity fifo_async;

architecture rtl of fifo_async is

  type t_memory is array (natural range 0 to 2 ** G_ADDR_WIDTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  -- No reset and no initial value, so block RAM is inferred.
  signal memory_r : t_memory;

  -- One bit wider than the address: the extra bit is what tells
  -- full from empty when the pointers are otherwise equal.
  signal wr_bin_r  : unsigned(G_ADDR_WIDTH downto 0) := (others => '0');
  signal wr_gray_r : std_logic_vector(G_ADDR_WIDTH downto 0) := (others => '0');
  signal rd_bin_r  : unsigned(G_ADDR_WIDTH downto 0) := (others => '0');
  signal rd_gray_r : std_logic_vector(G_ADDR_WIDTH downto 0) := (others => '0');

  -- Each pointer synchronised into the other domain. A new
  -- sample enters at index 1 and the settled value leaves at
  -- STAGES, which is the end the flags read: reading the other
  -- end compares against a value that has crossed nothing.
  type t_sync_array is array (1 to G_STAGES) of std_logic_vector(G_ADDR_WIDTH downto 0);

  signal rd_gray_wr_r : t_sync_array := (others => (others => '0'));
  signal wr_gray_rd_r : t_sync_array := (others => (others => '0'));

  signal wr_go : boolean;
  signal rd_go : boolean;
  signal full : std_logic;
  signal empty : std_logic;

begin

  wr_go <= wr_en_i = '1' and full = '0';
  rd_go <= rd_en_i = '1' and empty = '0';

  -- Write domain.
  p_memory : process (wr_clk) is
  begin
    if rising_edge(wr_clk) then
      if wr_go then
        memory_r(to_integer(wr_bin_r(G_ADDR_WIDTH - 1 downto 0))) <= wr_data_i;
      end if;
    end if;
  end process p_memory;

  p_write : process (wr_clk, wr_rst_n) is
  begin
    if wr_rst_n = '0' then
      wr_bin_r <= (others => '0');
      wr_gray_r <= (others => '0');
      rd_gray_wr_r <= (others => (others => '0'));
    elsif rising_edge(wr_clk) then
      rd_gray_wr_r <= rd_gray_r & rd_gray_wr_r(1 to G_STAGES - 1);

      if wr_go then
        wr_bin_r <= wr_bin_r + 1;
        -- Gray from the incremented binary value, in the same cycle:
        -- the two must never disagree.
        wr_gray_r <= std_logic_vector((wr_bin_r + 1) xor ((wr_bin_r + 1) srl 1));
      end if;
    end if;
  end process p_write;

  -- Read domain.
  p_read : process (rd_clk, rd_rst_n) is
  begin
    if rd_rst_n = '0' then
      rd_bin_r <= (others => '0');
      rd_gray_r <= (others => '0');
      wr_gray_rd_r <= (others => (others => '0'));
    elsif rising_edge(rd_clk) then
      wr_gray_rd_r <= wr_gray_r & wr_gray_rd_r(1 to G_STAGES - 1);

      if rd_go then
        rd_bin_r <= rd_bin_r + 1;
        rd_gray_r <= std_logic_vector((rd_bin_r + 1) xor ((rd_bin_r + 1) srl 1));
      end if;
    end if;
  end process p_read;

  -- Asynchronous read: the word is already there, because the
  -- write pointer only reaches this domain after it was written.
  rd_data_o <= memory_r(to_integer(rd_bin_r(G_ADDR_WIDTH - 1 downto 0)));

  -- Empty when the read pointer has caught the write pointer.
  empty <= '1' when rd_gray_r = wr_gray_rd_r(G_STAGES) else '0';

  -- Full when the write pointer has lapped the read pointer: the
  -- same address with the top two bits inverted.
  full <= '1' when wr_gray_r = ((not rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH)) & (not rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 1)) & rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 2 downto 0)) else '0';

  full_o <= full;
  empty_o <= empty;

end architecture rtl;
