-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_async   variant: upper_sync_high   case: defaults

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

-- Asynchronous FIFO.
--
-- The pointers are gray coded because they cross domains: a
-- binary pointer going from 0111 to 1000 changes four bits at
-- once, and a mid-transition sample could read any of sixteen
-- values. One bit changes per gray increment, so a sample is
-- always the old value or the new one.
--
-- Constrain both pointer crossings with set_max_delay
-- -datapath_only. The memory is not constrained: the write
-- pointer reaching the reader is what makes the data safe.
ENTITY fifo_async IS
  GENERIC (
    G_WIDTH      : positive := 32;
    G_ADDR_WIDTH : positive := 4;
    G_STAGES     : positive := 2
  );
  PORT (
    wr_clk    : IN  std_logic;
    wr_rst_n  : IN  std_logic;
    wr_en_i   : IN  std_logic;
    wr_data_i : IN  std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    full_o    : OUT std_logic;
    rd_clk    : IN  std_logic;
    rd_rst_n  : IN  std_logic;
    rd_en_i   : IN  std_logic;
    rd_data_o : OUT std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    empty_o   : OUT std_logic
  );
END ENTITY fifo_async;

ARCHITECTURE rtl OF fifo_async IS

  TYPE t_memory IS ARRAY (natural RANGE 0 TO 2 ** G_ADDR_WIDTH - 1) OF std_logic_vector(G_WIDTH - 1 DOWNTO 0);

  -- No reset and no initial value, so block RAM is inferred.
  SIGNAL memory_r : t_memory;

  -- One bit wider than the address: the extra bit is what tells
  -- full from empty when the pointers are otherwise equal.
  SIGNAL wr_bin_r  : unsigned(G_ADDR_WIDTH DOWNTO 0) := (OTHERS => '0');
  SIGNAL wr_gray_r : std_logic_vector(G_ADDR_WIDTH DOWNTO 0) := (OTHERS => '0');
  SIGNAL rd_bin_r  : unsigned(G_ADDR_WIDTH DOWNTO 0) := (OTHERS => '0');
  SIGNAL rd_gray_r : std_logic_vector(G_ADDR_WIDTH DOWNTO 0) := (OTHERS => '0');

  -- Each pointer synchronised into the other domain. A new
  -- sample enters at index 1 and the settled value leaves at
  -- STAGES, which is the end the flags read: reading the other
  -- end compares against a value that has crossed nothing.
  TYPE t_sync_array IS ARRAY (1 TO G_STAGES) OF std_logic_vector(G_ADDR_WIDTH DOWNTO 0);

  SIGNAL rd_gray_wr_r : t_sync_array := (OTHERS => (OTHERS => '0'));
  SIGNAL wr_gray_rd_r : t_sync_array := (OTHERS => (OTHERS => '0'));

  SIGNAL wr_go : boolean;
  SIGNAL rd_go : boolean;
  SIGNAL full : std_logic;
  SIGNAL empty : std_logic;

BEGIN

  wr_go <= wr_en_i = '1' AND full = '0';
  rd_go <= rd_en_i = '1' AND empty = '0';

  -- Write domain.
  p_memory : PROCESS (wr_clk) IS
  BEGIN
    IF RISING_EDGE(wr_clk) THEN
      IF wr_go THEN
        memory_r(TO_INTEGER(wr_bin_r(G_ADDR_WIDTH - 1 DOWNTO 0))) <= wr_data_i;
      END IF;
    END IF;
  END PROCESS p_memory;

  p_write : PROCESS (wr_clk, wr_rst_n) IS
  BEGIN
    IF wr_rst_n = '0' THEN
      wr_bin_r <= (OTHERS => '0');
      wr_gray_r <= (OTHERS => '0');
      rd_gray_wr_r <= (OTHERS => (OTHERS => '0'));
    ELSIF RISING_EDGE(wr_clk) THEN
      rd_gray_wr_r <= rd_gray_r & rd_gray_wr_r(1 TO G_STAGES - 1);

      IF wr_go THEN
        wr_bin_r <= wr_bin_r + 1;
        -- Gray from the incremented binary value, in the same cycle:
        -- the two must never disagree.
        wr_gray_r <= STD_LOGIC_VECTOR((wr_bin_r + 1) XOR ((wr_bin_r + 1) SRL 1));
      END IF;
    END IF;
  END PROCESS p_write;

  -- Read domain.
  p_read : PROCESS (rd_clk, rd_rst_n) IS
  BEGIN
    IF rd_rst_n = '0' THEN
      rd_bin_r <= (OTHERS => '0');
      rd_gray_r <= (OTHERS => '0');
      wr_gray_rd_r <= (OTHERS => (OTHERS => '0'));
    ELSIF RISING_EDGE(rd_clk) THEN
      wr_gray_rd_r <= wr_gray_r & wr_gray_rd_r(1 TO G_STAGES - 1);

      IF rd_go THEN
        rd_bin_r <= rd_bin_r + 1;
        rd_gray_r <= STD_LOGIC_VECTOR((rd_bin_r + 1) XOR ((rd_bin_r + 1) SRL 1));
      END IF;
    END IF;
  END PROCESS p_read;

  -- Asynchronous read: the word is already there, because the
  -- write pointer only reaches this domain after it was written.
  rd_data_o <= memory_r(TO_INTEGER(rd_bin_r(G_ADDR_WIDTH - 1 DOWNTO 0)));

  -- Empty when the read pointer has caught the write pointer.
  empty <= '1' WHEN rd_gray_r = wr_gray_rd_r(G_STAGES) ELSE '0';

  -- Full when the write pointer has lapped the read pointer: the
  -- same address with the top two bits inverted.
  full <= '1' WHEN wr_gray_r = (
      (NOT rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH)) &
      (NOT rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 1)) &
      rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 2 DOWNTO 0)
    ) ELSE '0';

  full_o <= full;
  empty_o <= empty;

END ARCHITECTURE rtl;
