-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_sync   variant: upper_sync_high   case: name_gold_name

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

ENTITY gold_name IS
  GENERIC (
    G_WIDTH : positive := 8;
    G_DEPTH : positive := 16
  );
  PORT (
    clk       : IN  std_logic;
    rst       : IN  std_logic;
    wr_en_i   : IN  std_logic;
    wr_data_i : IN  std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    full_o    : OUT std_logic;
    rd_en_i   : IN  std_logic;
    rd_data_o : OUT std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    empty_o   : OUT std_logic
  );
END ENTITY gold_name;

ARCHITECTURE rtl OF gold_name IS

  TYPE t_memory IS ARRAY (0 TO G_DEPTH - 1) OF std_logic_vector(G_WIDTH - 1 DOWNTO 0);

  SIGNAL memory_r : t_memory;

  SIGNAL wr_ptr_r : natural RANGE 0 TO G_DEPTH - 1 := 0;
  SIGNAL rd_ptr_r : natural RANGE 0 TO G_DEPTH - 1 := 0;
  SIGNAL count_r  : natural RANGE 0 TO G_DEPTH := 0;

  SIGNAL wr_go : boolean;
  SIGNAL rd_go : boolean;

BEGIN

  -- A write to a full FIFO, or a read from an empty one, is
  -- ignored: a misbehaving master must not desynchronise it.
  wr_go <= wr_en_i = '1' AND count_r < G_DEPTH;
  rd_go <= rd_en_i = '1' AND count_r > 0;

  -- No reset here: a reset on every element prevents block RAM
  -- inference on most tools.
  p_memory : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF wr_go THEN
        memory_r(wr_ptr_r) <= wr_data_i;
      END IF;
    END IF;
  END PROCESS p_memory;

  p_pointers : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        wr_ptr_r <= 0;
        rd_ptr_r <= 0;
        count_r <= 0;
      ELSE
        IF wr_go THEN
          wr_ptr_r <= (wr_ptr_r + 1) MOD G_DEPTH;
        END IF;

        IF rd_go THEN
          rd_ptr_r <= (rd_ptr_r + 1) MOD G_DEPTH;
        END IF;

        -- One update, so a simultaneous read and write is a no-op.
        IF wr_go AND NOT rd_go THEN
          count_r <= count_r + 1;
        ELSIF rd_go AND NOT wr_go THEN
          count_r <= count_r - 1;
        END IF;
      END IF;
    END IF;
  END PROCESS p_pointers;

  -- Asynchronous read, so the first word is available without a
  -- strobe. Register it for block RAM, at a cycle of latency.
  rd_data_o <= memory_r(rd_ptr_r);

  full_o <= '1' WHEN count_r = G_DEPTH ELSE '0';
  empty_o <= '1' WHEN count_r = 0 ELSE '0';

END ARCHITECTURE rtl;
