-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_async   variant: long_names   case: width_1

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Asynchronous FIFO.
--
-- The pointers are gray coded because they cross domains: a
-- binary pointer going from 0111 to 1000 changes four bits at
-- once, and a mid-transition sample could read any of sixteen
-- values. One bit changes per gray increment, so a sample is
-- always the old value or the new one.
--
-- Constrain both pointer crossings with set_max_delay
-- -datapath_only. The memory is not constrained: the write
-- pointer reaching the reader is what makes the data safe.
entity fifo_async is
  generic (
    G_WIDTH      : positive := 1;
    G_ADDR_WIDTH : positive := 4;
    G_STAGES     : positive := 2
  );
  port (
    wr_clk      : in  std_logic;
    wr_rst_n    : in  std_logic;
    s_wr_en_i   : in  std_logic;
    s_wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    s_full_o    : out std_logic;
    rd_clk      : in  std_logic;
    rd_rst_n    : in  std_logic;
    s_rd_en_i   : in  std_logic;
    s_rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0);
    s_empty_o   : out std_logic
  );
end entity fifo_async;

architecture rtl of fifo_async is

  type t_memory is array (natural range 0 to 2 ** G_ADDR_WIDTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  -- No reset and no initial value, so block RAM is inferred.
  signal s_memory_r : t_memory;

  -- One bit wider than the address: the extra bit is what tells
  -- full from empty when the pointers are otherwise equal.
  signal s_wr_bin_r  : unsigned(G_ADDR_WIDTH downto 0) := (others => '0');
  signal s_wr_gray_r : std_logic_vector(G_ADDR_WIDTH downto 0) := (others => '0');
  signal s_rd_bin_r  : unsigned(G_ADDR_WIDTH downto 0) := (others => '0');
  signal s_rd_gray_r : std_logic_vector(G_ADDR_WIDTH downto 0) := (others => '0');

  -- Each pointer synchronised into the other domain. A new
  -- sample enters at index 1 and the settled value leaves at
  -- STAGES, which is the end the flags read: reading the other
  -- end compares against a value that has crossed nothing.
  type t_sync_array is array (1 to G_STAGES) of std_logic_vector(G_ADDR_WIDTH downto 0);

  signal s_rd_gray_wr_r : t_sync_array := (others => (others => '0'));
  signal s_wr_gray_rd_r : t_sync_array := (others => (others => '0'));

  signal wr_go : boolean;
  signal rd_go : boolean;
  signal s_full : std_logic;
  signal s_empty : std_logic;

begin

  wr_go <= s_wr_en_i = '1' and s_full = '0';
  rd_go <= s_rd_en_i = '1' and s_empty = '0';

  -- Write domain.
  p_memory : process (wr_clk) is
  begin
    if rising_edge(wr_clk) then
      if wr_go then
        s_memory_r(to_integer(s_wr_bin_r(G_ADDR_WIDTH - 1 downto 0))) <= s_wr_data_i;
      end if;
    end if;
  end process p_memory;

  p_write : process (wr_clk, wr_rst_n) is
  begin
    if wr_rst_n = '0' then
      s_wr_bin_r <= (others => '0');
      s_wr_gray_r <= (others => '0');
      s_rd_gray_wr_r <= (others => (others => '0'));
    elsif rising_edge(wr_clk) then
      s_rd_gray_wr_r <= s_rd_gray_r & s_rd_gray_wr_r(1 to G_STAGES - 1);

      if wr_go then
        s_wr_bin_r <= s_wr_bin_r + 1;
        -- Gray from the incremented binary value, in the same cycle:
        -- the two must never disagree.
        s_wr_gray_r <= std_logic_vector((s_wr_bin_r + 1) xor ((s_wr_bin_r + 1) srl 1));
      end if;
    end if;
  end process p_write;

  -- Read domain.
  p_read : process (rd_clk, rd_rst_n) is
  begin
    if rd_rst_n = '0' then
      s_rd_bin_r <= (others => '0');
      s_rd_gray_r <= (others => '0');
      s_wr_gray_rd_r <= (others => (others => '0'));
    elsif rising_edge(rd_clk) then
      s_wr_gray_rd_r <= s_wr_gray_r & s_wr_gray_rd_r(1 to G_STAGES - 1);

      if rd_go then
        s_rd_bin_r <= s_rd_bin_r + 1;
        s_rd_gray_r <= std_logic_vector((s_rd_bin_r + 1) xor ((s_rd_bin_r + 1) srl 1));
      end if;
    end if;
  end process p_read;

  -- Asynchronous read: the word is already there, because the
  -- write pointer only reaches this domain after it was written.
  s_rd_data_o <= s_memory_r(to_integer(s_rd_bin_r(G_ADDR_WIDTH - 1 downto 0)));

  -- Empty when the read pointer has caught the write pointer.
  s_empty <= '1' when s_rd_gray_r = s_wr_gray_rd_r(G_STAGES) else '0';

  -- Full when the write pointer has lapped the read pointer: the
  -- same address with the top two bits inverted.
  s_full <= '1' when s_wr_gray_r = ((not s_rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH)) & (not s_rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 1)) & s_rd_gray_wr_r(G_STAGES)(G_ADDR_WIDTH - 2 downto 0)) else '0';

  s_full_o <= s_full;
  s_empty_o <= s_empty;

end architecture rtl;
