-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fifo_sync   variant: long_names   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;

entity gold_name is
  generic (
    G_WIDTH : positive := 8;
    G_DEPTH : positive := 16
  );
  port (
    axi_aclk    : in  std_logic;
    axi_aresetn : in  std_logic;
    s_wr_en_i   : in  std_logic;
    s_wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    s_full_o    : out std_logic;
    s_rd_en_i   : in  std_logic;
    s_rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0);
    s_empty_o   : out std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

  type t_memory is array (0 to G_DEPTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  signal s_memory_r : t_memory;

  signal s_wr_ptr_r : natural range 0 to G_DEPTH - 1 := 0;
  signal s_rd_ptr_r : natural range 0 to G_DEPTH - 1 := 0;
  signal s_count_r  : natural range 0 to G_DEPTH := 0;

  signal wr_go : boolean;
  signal rd_go : boolean;

begin

  -- A write to a full FIFO, or a read from an empty one, is
  -- ignored: a misbehaving master must not desynchronise it.
  wr_go <= s_wr_en_i = '1' and s_count_r < G_DEPTH;
  rd_go <= s_rd_en_i = '1' and s_count_r > 0;

  -- No reset here: a reset on every element prevents block RAM
  -- inference on most tools.
  p_memory : process (axi_aclk) is
  begin
    if rising_edge(axi_aclk) then
      if wr_go then
        s_memory_r(s_wr_ptr_r) <= s_wr_data_i;
      end if;
    end if;
  end process p_memory;

  p_pointers : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_wr_ptr_r <= 0;
      s_rd_ptr_r <= 0;
      s_count_r <= 0;
    elsif rising_edge(axi_aclk) then
      if wr_go then
        s_wr_ptr_r <= (s_wr_ptr_r + 1) mod G_DEPTH;
      end if;

      if rd_go then
        s_rd_ptr_r <= (s_rd_ptr_r + 1) mod G_DEPTH;
      end if;

      -- One update, so a simultaneous read and write is a no-op.
      if wr_go and not rd_go then
        s_count_r <= s_count_r + 1;
      elsif rd_go and not wr_go then
        s_count_r <= s_count_r - 1;
      end if;
    end if;
  end process p_pointers;

  -- Asynchronous read, so the first word is available without a
  -- strobe. Register it for block RAM, at a cycle of latency.
  s_rd_data_o <= s_memory_r(s_rd_ptr_r);

  s_full_o <= '1' when s_count_r = G_DEPTH else '0';
  s_empty_o <= '1' when s_count_r = 0 else '0';

end architecture rtl;
