-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: upper_sync_high   case: states_init__load__shift__done

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_main_state IS (init, load, shift, done);

  SIGNAL main_state_r    : t_main_state := init;
  SIGNAL main_state_next : t_main_state;

begin

  p_main_state : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        main_state_r <= init;
      ELSE
        main_state_r <= main_state_next;
      END IF;
    END IF;
  END PROCESS p_main_state;

  p_main_next : PROCESS (ALL) IS
  BEGIN
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    main_state_next <= main_state_r;

    CASE main_state_r IS
      WHEN init =>
        main_state_next <= load;

      WHEN load =>
        main_state_next <= shift;

      WHEN shift =>
        main_state_next <= done;

      WHEN done =>
        main_state_next <= init;

      WHEN OTHERS =>
        main_state_next <= init;
    END CASE;
  END PROCESS p_main_next;

end architecture golden;
