-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: no_reset   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_main_state is (idle, run, done);

  signal main_state_r    : t_main_state := idle;
  signal main_state_next : t_main_state;

begin

  p_main_state : process (clk) is
  begin
    if rising_edge(clk) then
      main_state_r <= main_state_next;
    end if;
  end process p_main_state;

  p_main_next : process (all) is
  begin
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    main_state_next <= main_state_r;

    case main_state_r is
      when idle =>
        main_state_next <= run;

      when run =>
        main_state_next <= done;

      when done =>
        main_state_next <= idle;

      when others =>
        main_state_next <= idle;
    end case;
  end process p_main_next;

end architecture golden;
