-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: upper_sync_high   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_gold_name_state IS (idle, run, done);

  SIGNAL gold_name_state_r    : t_gold_name_state := idle;
  SIGNAL gold_name_state_next : t_gold_name_state;

begin

  p_gold_name_state : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        gold_name_state_r <= idle;
      ELSE
        gold_name_state_r <= gold_name_state_next;
      END IF;
    END IF;
  END PROCESS p_gold_name_state;

  p_gold_name_next : PROCESS (ALL) IS
  BEGIN
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    gold_name_state_next <= gold_name_state_r;

    CASE gold_name_state_r IS
      WHEN idle =>
        gold_name_state_next <= run;

      WHEN run =>
        gold_name_state_next <= done;

      WHEN done =>
        gold_name_state_next <= idle;

      WHEN OTHERS =>
        gold_name_state_next <= idle;
    END CASE;
  END PROCESS p_gold_name_next;

end architecture golden;
