-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: upper_sync_high   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_main_state IS (idle, run, done);

  SIGNAL main_state_r    : t_main_state := idle;
  SIGNAL main_state_next : t_main_state;

begin

  p_main_state : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        main_state_r <= idle;
      ELSE
        main_state_r <= main_state_next;
      END IF;
    END IF;
  END PROCESS p_main_state;

  p_main_next : PROCESS (ALL) IS
  BEGIN
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    main_state_next <= main_state_r;

    CASE main_state_r IS
      WHEN idle =>
        main_state_next <= run;

      WHEN run =>
        main_state_next <= done;

      WHEN done =>
        main_state_next <= idle;

      WHEN OTHERS =>
        main_state_next <= idle;
    END CASE;
  END PROCESS p_main_next;

end architecture golden;
