-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: amd   case: states_init__load__shift__done

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_main_state is (init, load, shift, done);

  signal main_state_r    : t_main_state := init;
  signal main_state_next : t_main_state;

begin

  p_main_state : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      main_state_r <= init;
    elsif rising_edge(clk) then
      main_state_r <= main_state_next;
    end if;
  end process p_main_state;

  p_main_next : process (all) is
  begin
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    main_state_next <= main_state_r;

    case main_state_r is
      when init =>
        main_state_next <= load;

      when load =>
        main_state_next <= shift;

      when shift =>
        main_state_next <= done;

      when done =>
        main_state_next <= init;

      when others =>
        main_state_next <= init;
    end case;
  end process p_main_next;

end architecture golden;
