-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: amd   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_gold_name_state is (idle, run, done);

  signal gold_name_state_r    : t_gold_name_state := idle;
  signal gold_name_state_next : t_gold_name_state;

begin

  p_gold_name_state : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      gold_name_state_r <= idle;
    elsif rising_edge(clk) then
      gold_name_state_r <= gold_name_state_next;
    end if;
  end process p_gold_name_state;

  p_gold_name_next : process (all) is
  begin
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    gold_name_state_next <= gold_name_state_r;

    case gold_name_state_r is
      when idle =>
        gold_name_state_next <= run;

      when run =>
        gold_name_state_next <= done;

      when done =>
        gold_name_state_next <= idle;

      when others =>
        gold_name_state_next <= idle;
    end case;
  end process p_gold_name_next;

end architecture golden;
