-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: fsm   variant: long_names   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_gold_name_state is (idle, run, done);

  signal s_gold_name_state_r  : t_gold_name_state := idle;
  signal gold_name_state_next : t_gold_name_state;

begin

  p_gold_name_state : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_gold_name_state_r <= idle;
    elsif rising_edge(axi_aclk) then
      s_gold_name_state_r <= gold_name_state_next;
    end if;
  end process p_gold_name_state;

  p_gold_name_next : process (all) is
  begin
    -- Default assignment, so every path is covered and the logic
    -- stays combinational rather than inferring a latch.
    gold_name_state_next <= s_gold_name_state_r;

    case s_gold_name_state_r is
      when idle =>
        gold_name_state_next <= run;

      when run =>
        gold_name_state_next <= done;

      when done =>
        gold_name_state_next <= idle;

      when others =>
        gold_name_state_next <= idle;
    end case;
  end process p_gold_name_next;

end architecture golden;
