-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: mux   variant: long_names   case: inputs_2

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_mux_inputs is array (0 to 1) of std_logic_vector(7 downto 0);

  signal mux_in : t_mux_inputs;
  signal mux_sel : natural range 0 to 1;
  signal mux_out : std_logic_vector(7 downto 0);

begin

  mux_out <= mux_in(mux_sel);

end architecture golden;
