-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: mux   variant: upper_sync_high   case: inputs_2

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_mux_inputs IS ARRAY (0 TO 1) OF std_logic_vector(7 DOWNTO 0);

  SIGNAL mux_in : t_mux_inputs;
  SIGNAL mux_sel : natural RANGE 0 TO 1;
  SIGNAL mux_out : std_logic_vector(7 DOWNTO 0);

begin

  mux_out <= mux_in(mux_sel);

end architecture golden;
