-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: mux   variant: upper_sync_high   case: output_registered

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_mux_inputs IS ARRAY (0 TO 3) OF std_logic_vector(7 DOWNTO 0);

  SIGNAL mux_in : t_mux_inputs;
  SIGNAL mux_sel : natural RANGE 0 TO 3;
  SIGNAL mux_out_r : std_logic_vector(7 DOWNTO 0);

begin

  p_mux : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        mux_out_r <= (OTHERS => '0');
      ELSE
        mux_out_r <= mux_in(mux_sel);
      END IF;
    END IF;
  END PROCESS p_mux;

end architecture golden;
