-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: mux   variant: default   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_gold_sig_inputs is array (0 to 3) of std_logic_vector(7 downto 0);

  signal gold_sig_in : t_gold_sig_inputs;
  signal gold_sig_sel : natural range 0 to 3;
  signal gold_sig_out : std_logic_vector(7 downto 0);

begin

  gold_sig_out <= gold_sig_in(gold_sig_sel);

end architecture golden;
