-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: mux   variant: upper_sync_high   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_gold_sig_inputs IS ARRAY (0 TO 3) OF std_logic_vector(7 DOWNTO 0);

  SIGNAL gold_sig_in : t_gold_sig_inputs;
  SIGNAL gold_sig_sel : natural RANGE 0 TO 3;
  SIGNAL gold_sig_out : std_logic_vector(7 DOWNTO 0);

begin

  gold_sig_out <= gold_sig_in(gold_sig_sel);

end architecture golden;
