-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: package   variant: intel   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;

package gold_name is

end package gold_name;
