-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: package   variant: upper_sync_high   case: name_gold_name

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

PACKAGE gold_name IS

END PACKAGE gold_name;
