-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: package   variant: long_names   case: defaults

library ieee;
  use ieee.std_logic_1164.all;

package my_pkg is

end package my_pkg;
