-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: package   variant: upper_sync_high   case: defaults

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

PACKAGE my_pkg IS

END PACKAGE my_pkg;
