-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: long_names   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_gold_sig_pipe is array (1 to 3) of std_logic_vector(7 downto 0);

  signal gold_sig_in : std_logic_vector(7 downto 0);
  signal s_gold_sig_pipe_r : t_gold_sig_pipe;
  signal gold_sig_delayed : std_logic_vector(7 downto 0);

begin

  p_gold_sig_pipe : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_gold_sig_pipe_r <= (others => (others => '0'));
    elsif rising_edge(axi_aclk) then
      s_gold_sig_pipe_r(1) <= gold_sig_in;
      s_gold_sig_pipe_r(2 to 3) <= s_gold_sig_pipe_r(1 to 2);
    end if;
  end process p_gold_sig_pipe;

  gold_sig_delayed <= s_gold_sig_pipe_r(3);

end architecture golden;
