-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: amd   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_gold_sig_pipe is array (1 to 3) of std_logic_vector(7 downto 0);

  signal gold_sig_in : std_logic_vector(7 downto 0);
  signal gold_sig_pipe_r : t_gold_sig_pipe;
  signal gold_sig_delayed : std_logic_vector(7 downto 0);

begin

  p_gold_sig_pipe : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      gold_sig_pipe_r <= (others => (others => '0'));
    elsif rising_edge(clk) then
      gold_sig_pipe_r(1) <= gold_sig_in;
      gold_sig_pipe_r(2 to 3) <= gold_sig_pipe_r(1 to 2);
    end if;
  end process p_gold_sig_pipe;

  gold_sig_delayed <= gold_sig_pipe_r(3);

end architecture golden;
