-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: upper_sync_high   case: stages_256

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_data_pipe IS ARRAY (1 TO 256) OF std_logic_vector(7 DOWNTO 0);

  SIGNAL data_in : std_logic_vector(7 DOWNTO 0);
  SIGNAL data_pipe_r : t_data_pipe;
  SIGNAL data_delayed : std_logic_vector(7 DOWNTO 0);

begin

  p_data_pipe : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        data_pipe_r <= (OTHERS => (OTHERS => '0'));
      ELSE
        data_pipe_r(1) <= data_in;
        data_pipe_r(2 TO 256) <= data_pipe_r(1 TO 255);
      END IF;
    END IF;
  END PROCESS p_data_pipe;

  data_delayed <= data_pipe_r(256);

end architecture golden;
