-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: upper_sync_high   case: sig_gold_sig

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  TYPE t_gold_sig_pipe IS ARRAY (1 TO 3) OF std_logic_vector(7 DOWNTO 0);

  SIGNAL gold_sig_in : std_logic_vector(7 DOWNTO 0);
  SIGNAL gold_sig_pipe_r : t_gold_sig_pipe;
  SIGNAL gold_sig_delayed : std_logic_vector(7 DOWNTO 0);

begin

  p_gold_sig_pipe : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        gold_sig_pipe_r <= (OTHERS => (OTHERS => '0'));
      ELSE
        gold_sig_pipe_r(1) <= gold_sig_in;
        gold_sig_pipe_r(2 TO 3) <= gold_sig_pipe_r(1 TO 2);
      END IF;
    END IF;
  END PROCESS p_gold_sig_pipe;

  gold_sig_delayed <= gold_sig_pipe_r(3);

end architecture golden;
