-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: long_names   case: stages_256

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_data_pipe is array (1 to 256) of std_logic_vector(7 downto 0);

  signal data_in : std_logic_vector(7 downto 0);
  signal s_data_pipe_r : t_data_pipe;
  signal data_delayed : std_logic_vector(7 downto 0);

begin

  p_data_pipe : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_data_pipe_r <= (others => (others => '0'));
    elsif rising_edge(axi_aclk) then
      s_data_pipe_r(1) <= data_in;
      s_data_pipe_r(2 to 256) <= s_data_pipe_r(1 to 255);
    end if;
  end process p_data_pipe;

  data_delayed <= s_data_pipe_r(256);

end architecture golden;
