-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: vhdl93   case: stages_1

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_data_pipe is array (1 to 1) of std_logic_vector(7 downto 0);

  signal data_in : std_logic_vector(7 downto 0);
  signal data_pipe_r : t_data_pipe;
  signal data_delayed : std_logic_vector(7 downto 0);

begin

  p_data_pipe : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      data_pipe_r <= (others => (others => '0'));
    elsif rising_edge(clk) then
      data_pipe_r(1) <= data_in;
    end if;
  end process p_data_pipe;

  data_delayed <= data_pipe_r(1);

end architecture golden;
