-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: pipeline   variant: no_reset   case: width_4096

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

  type t_data_pipe is array (1 to 3) of std_logic_vector(4095 downto 0);

  signal data_in : std_logic_vector(4095 downto 0);
  signal data_pipe_r : t_data_pipe;
  signal data_delayed : std_logic_vector(4095 downto 0);

begin

  p_data_pipe : process (clk) is
  begin
    if rising_edge(clk) then
      data_pipe_r(1) <= data_in;
      data_pipe_r(2 to 3) <= data_pipe_r(1 to 2);
    end if;
  end process p_data_pipe;

  data_delayed <= data_pipe_r(3);

end architecture golden;
