-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: process   variant: long_names   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    axi_aclk    : in std_logic;
    axi_aresetn : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

begin

  p_main : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      -- reset state
    elsif rising_edge(axi_aclk) then
      -- clocked logic
    end if;
  end process p_main;

end architecture golden;
