-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: process   variant: default   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk   : in std_logic;
    rst_n : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

begin

  p_main : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      -- reset state
    elsif rising_edge(clk) then
      -- clocked logic
    end if;
  end process p_main;

end architecture golden;
