-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: process   variant: no_reset   case: label_gold_label

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

begin

  p_gold_label : process (clk) is
  begin
    if rising_edge(clk) then
      -- clocked logic
    end if;
  end process p_gold_label;

end architecture golden;
