-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: process   variant: upper_sync_high   case: defaults

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

-- Wrapper added by scripts/golden.lua so the fragment can be analysed.
entity golden_wrapper is
  port (
    clk : in std_logic;
    rst : in std_logic
  );
end entity golden_wrapper;

architecture golden of golden_wrapper is

begin

  p_main : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        -- reset state
      ELSE
        -- clocked logic
      END IF;
    END IF;
  END PROCESS p_main;

end architecture golden;
