-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: ram_dp   variant: long_names   case: width_1

library ieee;
  use ieee.std_logic_1164.all;

entity ram_dp is
  generic (
    G_WIDTH : positive := 1;
    G_DEPTH : positive := 1024
  );
  port (
    axi_aclk    : in  std_logic;
    s_we_i      : in  std_logic;
    s_wr_addr_i : in  natural range 0 to G_DEPTH - 1;
    s_wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    s_rd_addr_i : in  natural range 0 to G_DEPTH - 1;
    s_rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0)
  );
end entity ram_dp;

architecture rtl of ram_dp is

  type t_memory is array (0 to G_DEPTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  -- No reset and no initial value: both prevent block RAM
  -- inference on some tools.
  signal s_memory_r : t_memory;

begin

  p_memory : process (axi_aclk) is
  begin
    if rising_edge(axi_aclk) then
      if s_we_i = '1' then
        s_memory_r(s_wr_addr_i) <= s_wr_data_i;
      end if;

      -- Read-first: a read of the address being written returns the
      -- old contents. Write-first needs an explicit bypass.
      s_rd_data_o <= s_memory_r(s_rd_addr_i);
    end if;
  end process p_memory;

end architecture rtl;
