-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: ram_dp   variant: upper_sync_high   case: depth_1048576

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;

ENTITY ram_dp IS
  GENERIC (
    G_WIDTH : positive := 32;
    G_DEPTH : positive := 1048576
  );
  PORT (
    clk       : IN  std_logic;
    we_i      : IN  std_logic;
    wr_addr_i : IN  natural RANGE 0 TO G_DEPTH - 1;
    wr_data_i : IN  std_logic_vector(G_WIDTH - 1 DOWNTO 0);
    rd_addr_i : IN  natural RANGE 0 TO G_DEPTH - 1;
    rd_data_o : OUT std_logic_vector(G_WIDTH - 1 DOWNTO 0)
  );
END ENTITY ram_dp;

ARCHITECTURE rtl OF ram_dp IS

  TYPE t_memory IS ARRAY (0 TO G_DEPTH - 1) OF std_logic_vector(G_WIDTH - 1 DOWNTO 0);

  -- No reset and no initial value: both prevent block RAM
  -- inference on some tools.
  SIGNAL memory_r : t_memory;

BEGIN

  p_memory : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF we_i = '1' THEN
        memory_r(wr_addr_i) <= wr_data_i;
      END IF;

      -- Read-first: a read of the address being written returns the
      -- old contents. Write-first needs an explicit bypass.
      rd_data_o <= memory_r(rd_addr_i);
    END IF;
  END PROCESS p_memory;

END ARCHITECTURE rtl;
