-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: ram_dp   variant: amd   case: defaults

library ieee;
  use ieee.std_logic_1164.all;

entity ram_dp is
  generic (
    G_WIDTH : positive := 32;
    G_DEPTH : positive := 1024
  );
  port (
    clk       : in  std_logic;
    we_i      : in  std_logic;
    wr_addr_i : in  natural range 0 to G_DEPTH - 1;
    wr_data_i : in  std_logic_vector(G_WIDTH - 1 downto 0);
    rd_addr_i : in  natural range 0 to G_DEPTH - 1;
    rd_data_o : out std_logic_vector(G_WIDTH - 1 downto 0)
  );
end entity ram_dp;

architecture rtl of ram_dp is

  type t_memory is array (0 to G_DEPTH - 1) of std_logic_vector(G_WIDTH - 1 downto 0);

  -- No reset and no initial value: both prevent block RAM
  -- inference on some tools.
  signal memory_r : t_memory;

begin

  p_memory : process (clk) is
  begin
    if rising_edge(clk) then
      if we_i = '1' then
        memory_r(wr_addr_i) <= wr_data_i;
      end if;

      -- Read-first: a read of the address being written returns the
      -- old contents. Write-first needs an explicit bypass.
      rd_data_o <= memory_r(rd_addr_i);
    end if;
  end process p_memory;

end architecture rtl;
