-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: wishbone_slave   variant: long_names   case: name_gold_name

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity gold_name is
  generic (
    G_REGISTERS : positive := 4;
    G_ADDR_WIDTH : positive := 2
  );
  port (
    axi_aclk    : in  std_logic;
    axi_aresetn : in  std_logic;
    wb_cyc_i    : in  std_logic;
    wb_stb_i    : in  std_logic;
    wb_we_i     : in  std_logic;
    wb_adr_i    : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    wb_dat_i    : in  std_logic_vector(31 downto 0);
    wb_sel_i    : in  std_logic_vector(3 downto 0);
    wb_dat_o    : out std_logic_vector(31 downto 0);
    wb_ack_o    : out std_logic;
    wb_err_o    : out std_logic
  );
end entity gold_name;

architecture rtl of gold_name is

  type t_registers is array (natural range 0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal s_reg_file_r : t_registers;
  signal s_index : natural;
  signal s_ack_r : std_logic;
  signal s_dat_r : std_logic_vector(31 downto 0);
  signal s_err_r : std_logic;

begin

  s_index <= to_integer(unsigned(wb_adr_i));

  p_wishbone : process (axi_aclk, axi_aresetn) is
  begin
    if axi_aresetn = '0' then
      s_reg_file_r <= (others => (others => '0'));
      s_ack_r <= '0';
      s_err_r <= '0';
      s_dat_r <= (others => '0');
    elsif rising_edge(axi_aclk) then
      -- ACK is a single cycle: held high the master would count
      -- one transfer as several.
      s_ack_r <= '0';
      s_err_r <= '0';

      if wb_cyc_i = '1' and wb_stb_i = '1' and s_ack_r = '0' then
        if s_index < G_REGISTERS then
          if wb_we_i = '1' then
            for byte in 0 to 3 loop
              if wb_sel_i(byte) = '1' then
                s_reg_file_r(s_index)(byte * 8 + 7 downto byte * 8) <=
                  wb_dat_i(byte * 8 + 7 downto byte * 8);
              end if;
            end loop;
          else
            s_dat_r <= s_reg_file_r(s_index);
          end if;
        else
          -- Outside the register file: ERR rather than a silent
          -- alias onto a real register.
          s_err_r <= '1';
          s_dat_r <= (others => '0');
        end if;

        s_ack_r <= '1';
      end if;
    end if;
  end process p_wishbone;

  wb_ack_o <= s_ack_r;
  wb_err_o <= s_err_r;
  wb_dat_o <= s_dat_r;

end architecture rtl;
