-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: wishbone_slave   variant: upper_sync_high   case: registers_1

LIBRARY ieee;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

ENTITY wb_regs IS
  GENERIC (
    G_REGISTERS : positive := 1;
    G_ADDR_WIDTH : positive := 1
  );
  PORT (
    clk      : IN  std_logic;
    rst      : IN  std_logic;
    wb_cyc_i : IN  std_logic;
    wb_stb_i : IN  std_logic;
    wb_we_i  : IN  std_logic;
    wb_adr_i : IN  std_logic_vector(G_ADDR_WIDTH - 1 DOWNTO 0);
    wb_dat_i : IN  std_logic_vector(31 DOWNTO 0);
    wb_sel_i : IN  std_logic_vector(3 DOWNTO 0);
    wb_dat_o : OUT std_logic_vector(31 DOWNTO 0);
    wb_ack_o : OUT std_logic;
    wb_err_o : OUT std_logic
  );
END ENTITY wb_regs;

ARCHITECTURE rtl OF wb_regs IS

  TYPE t_registers IS ARRAY (natural RANGE 0 TO G_REGISTERS - 1) OF std_logic_vector(31 DOWNTO 0);

  SIGNAL reg_file_r : t_registers;
  SIGNAL index : natural;
  SIGNAL ack_r : std_logic;
  SIGNAL dat_r : std_logic_vector(31 DOWNTO 0);
  SIGNAL err_r : std_logic;

BEGIN

  index <= TO_INTEGER(UNSIGNED(wb_adr_i));

  p_wishbone : PROCESS (clk) IS
  BEGIN
    IF RISING_EDGE(clk) THEN
      IF rst = '1' THEN
        reg_file_r <= (OTHERS => (OTHERS => '0'));
        ack_r <= '0';
        err_r <= '0';
        dat_r <= (OTHERS => '0');
      ELSE
        -- ACK is a single cycle: held high the master would count
        -- one transfer as several.
        ack_r <= '0';
        err_r <= '0';

        IF wb_cyc_i = '1' AND wb_stb_i = '1' AND ack_r = '0' THEN
          IF index < G_REGISTERS THEN
            IF wb_we_i = '1' THEN
              FOR byte IN 0 TO 3 LOOP
                IF wb_sel_i(byte) = '1' THEN
                  reg_file_r(index)(byte * 8 + 7 DOWNTO byte * 8) <=
                    wb_dat_i(byte * 8 + 7 DOWNTO byte * 8);
                END IF;
              END LOOP;
            ELSE
              dat_r <= reg_file_r(index);
            END IF;
          ELSE
            -- Outside the register file: ERR rather than a silent
            -- alias onto a real register.
            err_r <= '1';
            dat_r <= (OTHERS => '0');
          END IF;

          ack_r <= '1';
        END IF;
      END IF;
    END IF;
  END PROCESS p_wishbone;

  wb_ack_o <= ack_r;
  wb_err_o <= err_r;
  wb_dat_o <= dat_r;

END ARCHITECTURE rtl;
