-- GENERATED by scripts/golden.lua -- do not edit by hand.
-- template: wishbone_slave   variant: intel   case: registers_1

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity wb_regs is
  generic (
    G_REGISTERS : positive := 1;
    G_ADDR_WIDTH : positive := 1
  );
  port (
    clk      : in  std_logic;
    rst_n    : in  std_logic;
    wb_cyc_i : in  std_logic;
    wb_stb_i : in  std_logic;
    wb_we_i  : in  std_logic;
    wb_adr_i : in  std_logic_vector(G_ADDR_WIDTH - 1 downto 0);
    wb_dat_i : in  std_logic_vector(31 downto 0);
    wb_sel_i : in  std_logic_vector(3 downto 0);
    wb_dat_o : out std_logic_vector(31 downto 0);
    wb_ack_o : out std_logic;
    wb_err_o : out std_logic
  );
end entity wb_regs;

architecture rtl of wb_regs is

  type t_registers is array (natural range 0 to G_REGISTERS - 1) of std_logic_vector(31 downto 0);

  signal reg_file_r : t_registers;
  signal index : natural;
  signal ack_r : std_logic;
  signal dat_r : std_logic_vector(31 downto 0);
  signal err_r : std_logic;

begin

  index <= to_integer(unsigned(wb_adr_i));

  p_wishbone : process (clk, rst_n) is
  begin
    if rst_n = '0' then
      reg_file_r <= (others => (others => '0'));
      ack_r <= '0';
      err_r <= '0';
      dat_r <= (others => '0');
    elsif rising_edge(clk) then
      -- ACK is a single cycle: held high the master would count
      -- one transfer as several.
      ack_r <= '0';
      err_r <= '0';

      if wb_cyc_i = '1' and wb_stb_i = '1' and ack_r = '0' then
        if index < G_REGISTERS then
          if wb_we_i = '1' then
            for byte in 0 to 3 loop
              if wb_sel_i(byte) = '1' then
                reg_file_r(index)(byte * 8 + 7 downto byte * 8) <=
                  wb_dat_i(byte * 8 + 7 downto byte * 8);
              end if;
            end loop;
          else
            dat_r <= reg_file_r(index);
          end if;
        else
          -- Outside the register file: ERR rather than a silent
          -- alias onto a real register.
          err_r <= '1';
          dat_r <= (others => '0');
        end if;

        ack_r <= '1';
      end if;
    end if;
  end process p_wishbone;

  wb_ack_o <= ack_r;
  wb_err_o <= err_r;
  wb_dat_o <= dat_r;

end architecture rtl;
